//! Issue #72: `penalized_glm::fit_negbinomial` with an estimated theta and
//! `fit_tweedie` were 15-40x slower than `fit_poisson` on large `n`.
//!
//! * Negative binomial: the `MASS::glm.nb` alternation now warm-starts every IRLS
//!   fit, updates theta from the previous round's means exactly as MASS does (so
//!   on near-Poisson data, where the ML theta diverges, it stops after one round
//!   instead of 25), skips the reporting work in the intermediate fits and
//!   evaluates the digamma / trigamma / lgamma sums once per distinct count.
//! * Tweedie: the series density in the log-likelihood is accumulated in one
//!   streaming pass without per-row allocation or double evaluation.
//!
//! The reference values come from R 4.x, `MASS::glm.nb(y ~ x1 + x2)` on the data
//! generated by [`data`] (written to CSV and read back in R).

use anofox_regression::solvers::penalized_glm::{
    fit_negbinomial, fit_poisson, fit_tweedie, NegBinomialOptions, PoissonOptions, TweedieOptions,
};
use std::time::{Duration, Instant};

struct Lcg(u64);

impl Lcg {
    fn u(&mut self) -> f64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        ((self.0 >> 11) as f64) / ((1u64 << 53) as f64)
    }

    fn n(&mut self) -> f64 {
        let (a, b) = (self.u().max(1e-300), self.u());
        (-2.0 * a.ln()).sqrt() * (2.0 * std::f64::consts::PI * b).cos()
    }
}

/// `(y_count, y_tweedie, [x1, x2])`. With `overdispersed` the counts are
/// Poisson-lognormal (theta around 2.5); otherwise they follow the issue's
/// recipe `floor(exp(0.2 + 0.08 x1 - 0.1 x2) * (0.5 + u) * 2)`, which is
/// underdispersed, so the ML theta diverges.
fn data(n: usize, overdispersed: bool) -> (Vec<f64>, Vec<f64>, Vec<Vec<f64>>) {
    let mut r = Lcg(42);
    let (mut x1, mut x2, mut y, mut pos) = (
        Vec::with_capacity(n),
        Vec::with_capacity(n),
        Vec::with_capacity(n),
        Vec::with_capacity(n),
    );
    for _ in 0..n {
        let a = r.u() * 10.0;
        let b = r.u() * 5.0 - 2.5;
        let u = r.u();
        x1.push(a);
        x2.push(b);
        if overdispersed {
            let lam = (0.2 + 0.08 * a - 0.1 * b).exp() * (0.6 * r.n()).exp();
            let (mut k, mut pr, l) = (0.0, 1.0, (-lam).exp());
            loop {
                pr *= r.u();
                if pr < l {
                    break;
                }
                k += 1.0;
            }
            y.push(k);
        } else {
            y.push(((0.2 + 0.08 * a - 0.1 * b).exp() * (0.5 + u) * 2.0).floor());
        }
        let p = (0.5 + 0.1 * a + 0.3 * r.n()).exp();
        pos.push(if r.u() < 0.3 { 0.0 } else { p });
    }
    (y, pos, vec![x1, x2])
}

#[test]
fn negbinomial_estimated_theta_matches_mass_glm_nb() {
    let (y, _, x) = data(5000, true);
    let fit = fit_negbinomial(&y, &x, &NegBinomialOptions::default()).unwrap();
    // MASS::glm.nb(y ~ x1 + x2)
    let r_coef = [0.400174600315068, 0.077985742042916, -0.099189222783886];
    let r_theta = 2.41333026591;
    let r_loglik = -9730.82452950684;

    let got = [
        fit.core.intercept.unwrap(),
        fit.core.coefficients[0],
        fit.core.coefficients[1],
    ];
    for (g, r) in got.iter().zip(r_coef) {
        assert!((g - r).abs() < 1e-8, "coef {g} vs MASS {r}");
    }
    let theta = fit.core.dispersion.unwrap();
    assert!((theta - r_theta).abs() / r_theta < 1e-7, "theta {theta}");
    assert!(
        (fit.log_likelihood - r_loglik).abs() < 1e-6,
        "loglik {}",
        fit.log_likelihood
    );
}

#[test]
fn negbinomial_on_near_poisson_data_reaches_the_poisson_limit() {
    // MASS reports theta -> infinity (theta.ml "iteration limit reached"); the
    // coefficients are the Poisson ones.
    let (y, _, x) = data(3000, false);
    let nb = fit_negbinomial(&y, &x, &NegBinomialOptions::default()).unwrap();
    let po = fit_poisson(&y, &x, &PoissonOptions::default()).unwrap();
    assert!(
        nb.core.dispersion.unwrap() > 1e4,
        "theta {:?}",
        nb.core.dispersion
    );
    assert!((nb.core.intercept.unwrap() - po.core.intercept.unwrap()).abs() < 1e-4);
    for (a, b) in nb.core.coefficients.iter().zip(&po.core.coefficients) {
        assert!((a - b).abs() < 1e-4, "{a} vs {b}");
    }
}

fn best_of<T>(runs: usize, f: impl Fn() -> T) -> Duration {
    (0..runs)
        .map(|_| {
            let t = Instant::now();
            std::hint::black_box(f());
            t.elapsed()
        })
        .min()
        .unwrap()
}

/// Performance regression gate, relative to `fit_poisson` on the same data so it
/// does not depend on the machine. Before the fix (250k rows) the estimated-theta
/// negative binomial took ~40x and Tweedie ~3x the Poisson time; now they take
/// ~2.5x and ~2x. Ignored in debug builds (run with `cargo test --release`).
#[test]
#[cfg_attr(debug_assertions, ignore = "timing test; run with --release")]
fn negbinomial_and_tweedie_cost_a_small_multiple_of_poisson() {
    let (y, pos, x) = data(250_000, false);
    let poisson = best_of(2, || {
        fit_poisson(&y, &x, &PoissonOptions::default()).unwrap()
    });
    let negbin = best_of(2, || {
        fit_negbinomial(&y, &x, &NegBinomialOptions::default()).unwrap()
    });
    let tweedie = best_of(2, || {
        fit_tweedie(
            &pos,
            &x,
            &TweedieOptions {
                power: 1.5,
                ..Default::default()
            },
        )
        .unwrap()
    });
    let nb_ratio = negbin.as_secs_f64() / poisson.as_secs_f64();
    let tw_ratio = tweedie.as_secs_f64() / poisson.as_secs_f64();
    eprintln!("poisson {poisson:?}, negbin {negbin:?} ({nb_ratio:.1}x), tweedie {tweedie:?} ({tw_ratio:.1}x)");
    assert!(
        nb_ratio < 8.0,
        "negative binomial is {nb_ratio:.1}x Poisson"
    );
    assert!(tw_ratio < 6.0, "Tweedie is {tw_ratio:.1}x Poisson");
}
