//! GammaRegressor validation against R `glm(family = Gamma(link = "log"))`.
//!
//! Reference values are generated by `tests/r_scripts/generate_gamma_validation.R`
//! and embedded into `tests/fixtures/gamma_validation.rs`. To regenerate:
//!
//! ```bash
//! Rscript tests/r_scripts/generate_gamma_validation.R \
//!     > tests/fixtures/gamma_validation.rs
//! ```

#![allow(dead_code)]

use anofox_regression::solvers::{FittedRegressor, GammaRegressor, Regressor};
use faer::{Col, Mat};

include!("fixtures/gamma_validation.rs");

const COEF_TOL: f64 = 1e-4;
const DEVIANCE_TOL: f64 = 1e-3;

#[test]
fn gamma_univariate_matches_r() {
    let n = N_GAMMA_UNI;
    let x = Mat::from_fn(n, 1, |i, _| X_GAMMA_UNI[i]);
    let y = Col::from_fn(n, |i| Y_GAMMA_UNI[i]);

    let fitted = GammaRegressor::builder()
        .with_intercept(true)
        .compute_inference(false)
        .max_iterations(100)
        .tolerance(1e-10)
        .build()
        .fit(&x, &y)
        .expect("Gamma fit failed");

    let result = fitted.result();
    let intercept = result.intercept.expect("intercept must be present");
    let coef = result.coefficients[0];

    assert!(
        (intercept - EXPECTED_INTERCEPT_GAMMA_UNI).abs() < COEF_TOL,
        "intercept {} vs R {}",
        intercept,
        EXPECTED_INTERCEPT_GAMMA_UNI
    );
    assert!(
        (coef - EXPECTED_COEF_GAMMA_UNI).abs() < COEF_TOL,
        "coef {} vs R {}",
        coef,
        EXPECTED_COEF_GAMMA_UNI
    );

    let deviance = fitted.inner().deviance;
    assert!(
        (deviance - EXPECTED_DEVIANCE_GAMMA_UNI).abs() < DEVIANCE_TOL,
        "deviance {} vs R {}",
        deviance,
        EXPECTED_DEVIANCE_GAMMA_UNI
    );
}

#[test]
fn gamma_multivariate_matches_r() {
    let n = N_GAMMA_MULTI;
    let x = Mat::from_fn(n, 2, |i, j| {
        if j == 0 {
            X1_GAMMA_MULTI[i]
        } else {
            X2_GAMMA_MULTI[i]
        }
    });
    let y = Col::from_fn(n, |i| Y_GAMMA_MULTI[i]);

    let fitted = GammaRegressor::builder()
        .with_intercept(true)
        .compute_inference(false)
        .max_iterations(100)
        .tolerance(1e-10)
        .build()
        .fit(&x, &y)
        .expect("Gamma fit failed");

    let result = fitted.result();
    let intercept = result.intercept.expect("intercept must be present");
    let c1 = result.coefficients[0];
    let c2 = result.coefficients[1];

    assert!(
        (intercept - EXPECTED_INTERCEPT_GAMMA_MULTI).abs() < COEF_TOL,
        "intercept {} vs R {}",
        intercept,
        EXPECTED_INTERCEPT_GAMMA_MULTI
    );
    assert!(
        (c1 - EXPECTED_COEF1_GAMMA_MULTI).abs() < COEF_TOL,
        "coef1 {} vs R {}",
        c1,
        EXPECTED_COEF1_GAMMA_MULTI
    );
    assert!(
        (c2 - EXPECTED_COEF2_GAMMA_MULTI).abs() < COEF_TOL,
        "coef2 {} vs R {}",
        c2,
        EXPECTED_COEF2_GAMMA_MULTI
    );

    let deviance = fitted.inner().deviance;
    assert!(
        (deviance - EXPECTED_DEVIANCE_GAMMA_MULTI).abs() < DEVIANCE_TOL,
        "deviance {} vs R {}",
        deviance,
        EXPECTED_DEVIANCE_GAMMA_MULTI
    );
}
