//! PassiveAggressiveRegressor validation against scikit-learn 1.5.2.
//!
//! Reference values are generated by
//! `validation/python/generate_pa_validation.py` with `shuffle=False` so
//! the per-epoch traversal order is the data order, matching ours.

#![allow(dead_code)]

use anofox_regression::solvers::{FittedRegressor, PaLoss, PassiveAggressiveRegressor, Regressor};
use faer::{Col, Mat};

include!("fixtures/pa_validation.rs");

/// Tolerance covers minor floating-point ordering differences between
/// our update implementation and sklearn's Cython kernel; the algorithm
/// itself is deterministic with `shuffle=False`. In practice we match
/// sklearn to ~1e-2 on every fixture; we set the band slightly looser to
/// absorb sklearn version-to-version drift.
const TOL: f64 = 2e-2;

#[test]
fn pa1_univariate_matches_sklearn() {
    let n = N_PA1_UNI;
    let x = Mat::from_fn(n, 1, |i, _| X_PA1_UNI[i]);
    let y = Col::from_fn(n, |i| Y_PA1_UNI[i]);

    let fitted = PassiveAggressiveRegressor::builder()
        .c(1.0)
        .epsilon(0.1)
        .max_iter(50)
        .tolerance(1e-6)
        .shuffle(false)
        .loss(PaLoss::EpsilonInsensitive)
        .build()
        .fit(&x, &y)
        .unwrap();

    let intercept = fitted.result().intercept.unwrap();
    let coef = fitted.result().coefficients[0];

    assert!(
        (intercept - EXPECTED_INTERCEPT_PA1_UNI).abs() < TOL,
        "intercept {} vs sklearn {}",
        intercept,
        EXPECTED_INTERCEPT_PA1_UNI
    );
    assert!(
        (coef - EXPECTED_COEF_PA1_UNI).abs() < TOL,
        "coef {} vs sklearn {}",
        coef,
        EXPECTED_COEF_PA1_UNI
    );
}

#[test]
fn pa1_multivariate_matches_sklearn() {
    let n = N_PA1_MULTI;
    let p = P_PA1_MULTI;
    let x = Mat::from_fn(n, p, |i, j| X_PA1_MULTI_FLAT[i * p + j]);
    let y = Col::from_fn(n, |i| Y_PA1_MULTI[i]);

    let fitted = PassiveAggressiveRegressor::builder()
        .c(1.0)
        .epsilon(0.1)
        .max_iter(100)
        .tolerance(1e-6)
        .shuffle(false)
        .loss(PaLoss::EpsilonInsensitive)
        .build()
        .fit(&x, &y)
        .unwrap();

    let intercept = fitted.result().intercept.unwrap();
    let coefs = &fitted.result().coefficients;
    assert!(
        (intercept - EXPECTED_INTERCEPT_PA1_MULTI).abs() < TOL,
        "intercept {} vs sklearn {}",
        intercept,
        EXPECTED_INTERCEPT_PA1_MULTI
    );
    for j in 0..p {
        assert!(
            (coefs[j] - EXPECTED_COEFS_PA1_MULTI[j]).abs() < TOL,
            "coef[{}] {} vs sklearn {}",
            j,
            coefs[j],
            EXPECTED_COEFS_PA1_MULTI[j]
        );
    }
}

#[test]
fn pa2_multivariate_matches_sklearn() {
    let n = N_PA2_MULTI;
    let p = P_PA2_MULTI;
    let x = Mat::from_fn(n, p, |i, j| X_PA2_MULTI_FLAT[i * p + j]);
    let y = Col::from_fn(n, |i| Y_PA2_MULTI[i]);

    let fitted = PassiveAggressiveRegressor::builder()
        .c(0.5)
        .epsilon(0.05)
        .max_iter(80)
        .tolerance(1e-6)
        .shuffle(false)
        .loss(PaLoss::SquaredEpsilonInsensitive)
        .build()
        .fit(&x, &y)
        .unwrap();

    let intercept = fitted.result().intercept.unwrap();
    let coefs = &fitted.result().coefficients;
    assert!(
        (intercept - EXPECTED_INTERCEPT_PA2_MULTI).abs() < TOL,
        "intercept {} vs sklearn {}",
        intercept,
        EXPECTED_INTERCEPT_PA2_MULTI
    );
    for j in 0..p {
        assert!(
            (coefs[j] - EXPECTED_COEFS_PA2_MULTI[j]).abs() < TOL,
            "coef[{}] {} vs sklearn {}",
            j,
            coefs[j],
            EXPECTED_COEFS_PA2_MULTI[j]
        );
    }
}
