//! R validation of the penalized GLM engine (#44) and the AFT model (#45).
//!
//! References: `glm`, `MASS::glm.nb`, `MASS::negative.binomial`, a Newton
//! posterior-mode fit written in R for the priors, and `survival::survreg`.
//! Generated by `tests/r_scripts/penalized_glm_aft_reference.R`.

#[path = "fixtures/penalized_glm_aft_reference.rs"]
mod reference;

use anofox_regression::prelude::{BinomialLink, PoissonLink};
use anofox_regression::solvers::aft::{fit_aft, AftDistribution, AftOptions, AftRegressor};
use anofox_regression::solvers::penalized_glm::{
    fit_negbinomial, fit_poisson, FittedPenalizedGlm, NegBinomialOptions, PenalizedGlmFamily,
    PenalizedGlmRegressor, PoissonOptions, PriorSpec, VcovType,
};
use faer::{Col, Mat};
use reference::*;

fn rel_close(a: f64, b: f64, tol: f64, what: &str) {
    let err = (a - b).abs() / b.abs().max(1.0);
    assert!(err < tol, "{what}: got {a}, R {b} (rel err {err:e})");
}

fn design() -> Mat<f64> {
    Mat::from_fn(60, 2, |i, j| if j == 0 { X1[i] } else { X2[i] })
}

fn col(v: &[f64; 60]) -> Col<f64> {
    Col::from_fn(60, |i| v[i])
}

fn fit(family: PenalizedGlmFamily, y: &[f64; 60]) -> FittedPenalizedGlm {
    PenalizedGlmRegressor::builder()
        .family(family)
        .compute_inference(true)
        .tolerance(1e-10)
        .build()
        .fit(&design(), &col(y))
        .unwrap()
}

fn check_glm<const K: usize>(
    f: &FittedPenalizedGlm,
    coef: [f64; K],
    se: [f64; K],
    dev: [f64; 2],
    ll_aic: [f64; 2],
    what: &str,
) {
    assert!(f.converged(), "{what}: not converged");
    // K = p + 1 with an intercept, K = p without.
    let shift = K - f.coefficients().nrows();
    if shift == 1 {
        rel_close(f.intercept().unwrap(), coef[0], 1e-6, what);
        // #66: intercept inference matches R's first row.
        let inf = f.inference().unwrap();
        rel_close(inf.intercept_std_error.unwrap(), se[0], 1e-5, what);
        rel_close(
            inf.intercept_z_value.unwrap(),
            f.intercept().unwrap() / inf.intercept_std_error.unwrap(),
            1e-12,
            what,
        );
        assert!(inf.intercept_ci_lower.unwrap() < f.intercept().unwrap());
        assert!(inf.intercept_ci_upper.unwrap() > f.intercept().unwrap());
    } else {
        assert!(f.intercept().is_none(), "{what}: unexpected intercept");
    }
    for j in 0..f.coefficients().nrows() {
        rel_close(f.coefficients()[j], coef[j + shift], 1e-6, what);
        rel_close(f.std_errors().unwrap()[j], se[j + shift], 1e-5, what);
    }
    rel_close(f.deviance(), dev[0], 1e-7, what);
    rel_close(
        f.null_deviance(),
        dev[1],
        1e-7,
        &format!("{what} null deviance"),
    );
    rel_close(
        f.log_likelihood(),
        ll_aic[0],
        1e-7,
        &format!("{what} logLik"),
    );
    rel_close(f.aic(), ll_aic[1], 1e-7, &format!("{what} AIC"));
}

fn fit_with(
    family: PenalizedGlmFamily,
    y: &[f64; 60],
    intercept: bool,
    offset: bool,
) -> FittedPenalizedGlm {
    let mut b = PenalizedGlmRegressor::builder()
        .family(family)
        .with_intercept(intercept)
        .compute_inference(true)
        .tolerance(1e-10);
    if offset {
        b = b.offset(col(&OFFSET));
    }
    b.build().fit(&design(), &col(y)).unwrap()
}

#[test]
fn poisson_log_matches_glm() {
    let f = fit(PenalizedGlmFamily::poisson(), &Y_POIS);
    check_glm(&f, POIS_COEF, POIS_SE, POIS_DEV, POIS_LL_AIC, "poisson");
}

#[test]
fn poisson_with_offset_matches_glm() {
    let f = PenalizedGlmRegressor::builder()
        .family(PenalizedGlmFamily::poisson())
        .offset(col(&OFFSET))
        .compute_inference(true)
        .tolerance(1e-10)
        .build()
        .fit(&design(), &col(&Y_POIS))
        .unwrap();
    check_glm(
        &f,
        POIS_OFF_COEF,
        POIS_OFF_SE,
        POIS_OFF_DEV,
        POIS_OFF_LL_AIC,
        "poisson offset",
    );
    // predict_with_offset reproduces the fitted means.
    let mu = f.predict_with_offset(&design(), &col(&OFFSET));
    for (i, &m) in f.fitted_values().iter().enumerate() {
        rel_close(mu[i], m, 1e-12, "offset prediction");
    }
}

#[test]
fn poisson_sqrt_link_matches_glm() {
    let f = fit(PenalizedGlmFamily::Poisson(PoissonLink::Sqrt), &Y_POIS);
    rel_close(f.intercept().unwrap(), POIS_SQRT_COEF[0], 1e-6, "sqrt b0");
    rel_close(f.coefficients()[0], POIS_SQRT_COEF[1], 1e-6, "sqrt b1");
    rel_close(f.deviance(), POIS_SQRT_DEV[0], 1e-7, "sqrt deviance");
}

#[test]
fn binomial_links_match_glm() {
    let cases = [
        (
            BinomialLink::Logit,
            BIN_LOGIT_COEF,
            BIN_LOGIT_SE,
            BIN_LOGIT_DEV,
            BIN_LOGIT_LL_AIC,
        ),
        (
            BinomialLink::Probit,
            BIN_PROBIT_COEF,
            BIN_PROBIT_SE,
            BIN_PROBIT_DEV,
            BIN_PROBIT_LL_AIC,
        ),
        (
            BinomialLink::Cloglog,
            BIN_CLOGLOG_COEF,
            BIN_CLOGLOG_SE,
            BIN_CLOGLOG_DEV,
            BIN_CLOGLOG_LL_AIC,
        ),
    ];
    for (link, coef, se, dev, ll) in cases {
        let f = fit(PenalizedGlmFamily::Binomial(link), &Y_BIN);
        check_glm(&f, coef, se, dev, ll, &format!("binomial {link:?}"));
        assert!(!f.separation().has_separation);
    }
    // Logistic = binomial/logit plus training accuracy.
    let f = fit(PenalizedGlmFamily::logistic(), &Y_BIN);
    check_glm(
        &f,
        BIN_LOGIT_COEF,
        BIN_LOGIT_SE,
        BIN_LOGIT_DEV,
        BIN_LOGIT_LL_AIC,
        "logistic",
    );
    let acc = f.accuracy().unwrap();
    assert!((0.5..=1.0).contains(&acc));
}

#[test]
fn gamma_matches_glm() {
    let f = fit(PenalizedGlmFamily::gamma(), &Y_GAMMA);
    check_glm(&f, GAMMA_COEF, GAMMA_SE, GAMMA_DEV, GAMMA_LL_AIC, "gamma");
}

#[test]
fn tweedie_power_two_equals_gamma_coefficients() {
    let g = fit(PenalizedGlmFamily::gamma(), &Y_GAMMA);
    let t = fit(PenalizedGlmFamily::tweedie(2.0), &Y_GAMMA);
    for j in 0..2 {
        rel_close(
            t.coefficients()[j],
            g.coefficients()[j],
            1e-10,
            "tweedie p=2",
        );
    }
    let t1 = fit(PenalizedGlmFamily::tweedie(1.0), &Y_POIS);
    rel_close(t1.coefficients()[0], POIS_COEF[1], 1e-6, "tweedie p=1");
}

#[test]
fn negative_binomial_matches_mass_glm_nb() {
    let f = fit(PenalizedGlmFamily::negative_binomial(), &Y_NB);
    check_glm(&f, NB_COEF, NB_SE, NB_DEV, NB_LL_AIC, "glm.nb");
    rel_close(f.theta().unwrap(), NB_THETA, 1e-5, "theta");

    let fixed = fit(
        PenalizedGlmFamily::NegativeBinomial { theta: Some(2.5) },
        &Y_NB,
    );
    for j in 0..2 {
        rel_close(
            fixed.coefficients()[j],
            NB_FIXED_COEF[j + 1],
            1e-6,
            "nb fixed",
        );
        rel_close(
            fixed.std_errors().unwrap()[j],
            NB_FIXED_SE[j + 1],
            1e-5,
            "nb fixed se",
        );
    }
}

#[test]
fn gaussian_priors_give_the_posterior_mode_and_all_three_vcovs() {
    let priors = vec![
        PriorSpec::flat(),
        PriorSpec::normal(0.5, 0.5),
        PriorSpec::normal(0.0, 0.25),
    ];
    for (vcov, se) in [
        (VcovType::Laplace, POIS_PRIOR_SE_LAPLACE),
        (VcovType::Sandwich, POIS_PRIOR_SE_SANDWICH),
        (VcovType::Naive, POIS_PRIOR_SE_NAIVE),
    ] {
        let f = PenalizedGlmRegressor::builder()
            .family(PenalizedGlmFamily::poisson())
            .priors(priors.clone())
            .vcov_type(vcov)
            .compute_inference(true)
            .tolerance(1e-12)
            .build()
            .fit(&design(), &col(&Y_POIS))
            .unwrap();
        rel_close(f.intercept().unwrap(), POIS_PRIOR_COEF[0], 1e-7, "MAP b0");
        rel_close(f.coefficients()[0], POIS_PRIOR_COEF[1], 1e-7, "MAP b1");
        rel_close(f.coefficients()[1], POIS_PRIOR_COEF[2], 1e-7, "MAP b2");
        // Full covariance, intercept first.
        let v = f.vcov().unwrap();
        for j in 0..3 {
            rel_close(v[(j, j)].sqrt(), se[j], 1e-6, &format!("{vcov:?} se {j}"));
        }
    }
}

#[test]
fn column_major_entry_points_match_the_builder() {
    let x = vec![X1.to_vec(), X2.to_vec()];
    let opts = PoissonOptions {
        compute_inference: true,
        tolerance: 1e-10,
        ..Default::default()
    };
    let r = fit_poisson(&Y_POIS, &x, &opts).unwrap();
    let f = fit(PenalizedGlmFamily::poisson(), &Y_POIS);
    assert_eq!(r.core.coefficients[0], f.coefficients()[0]);
    assert_eq!(r.core.coefficients[1], f.coefficients()[1]);

    let nb = fit_negbinomial(&Y_NB, &x, &NegBinomialOptions::default()).unwrap();
    rel_close(nb.core.dispersion.unwrap(), NB_THETA, 1e-5, "nb theta (fn)");
}

fn aft_check(
    dist: AftDistribution,
    coef: [f64; 3],
    scale: f64,
    ll: [f64; 2],
    se: &[f64],
    q: [f64; 3],
) {
    let event: Vec<bool> = EVENT.iter().map(|&e| e == 1.0).collect();
    let f = AftRegressor::builder()
        .distribution(dist)
        .compute_inference(true)
        .build()
        .fit(&design(), &col(&TIME), &event)
        .unwrap();
    let what = format!("{dist:?}");
    assert!(f.converged(), "{what}");
    rel_close(f.intercept().unwrap(), coef[0], 1e-6, &what);
    rel_close(f.coefficients()[0], coef[1], 1e-6, &what);
    rel_close(f.coefficients()[1], coef[2], 1e-6, &what);
    rel_close(f.scale(), scale, 1e-6, &what);
    rel_close(f.null_log_likelihood(), ll[0], 1e-7, &what);
    rel_close(f.log_likelihood(), ll[1], 1e-7, &what);
    let inf = f.inference().unwrap();
    rel_close(inf.intercept_std_error.unwrap(), se[0], 1e-5, &what);
    // #66: the intercept carries the full Wald row, like the slopes.
    let b0 = f.intercept().unwrap();
    let se0 = inf.intercept_std_error.unwrap();
    rel_close(inf.intercept_z_value.unwrap(), b0 / se0, 1e-12, &what);
    let zq = (inf.ci_upper[0] - f.coefficients()[0]) / inf.std_errors[0];
    rel_close(inf.intercept_ci_lower.unwrap(), b0 - zq * se0, 1e-10, &what);
    rel_close(inf.intercept_ci_upper.unwrap(), b0 + zq * se0, 1e-10, &what);
    assert!(inf.intercept_p_value.unwrap() >= 0.0 && inf.intercept_p_value.unwrap() <= 1.0);
    rel_close(inf.std_errors[0], se[1], 1e-5, &what);
    rel_close(inf.std_errors[1], se[2], 1e-5, &what);
    if se.len() == 4 {
        rel_close(inf.log_scale_std_error.unwrap(), se[3], 1e-5, &what);
    } else {
        assert!(inf.log_scale_std_error.is_none());
    }
    let x0 = Mat::from_fn(1, 2, |_, j| [0.3, -0.2][j]);
    for (k, p) in [0.25, 0.5, 0.9].into_iter().enumerate() {
        rel_close(
            f.predict_quantile(&x0, p)[0],
            q[k],
            1e-6,
            &format!("{what} q{p}"),
        );
        // survival at the predicted quantile is 1 - p.
        let s = f.predict_survival(&x0, f.predict_quantile(&x0, p)[0])[0];
        rel_close(s, 1.0 - p, 1e-9, &format!("{what} S(q)"));
    }

    // The column-major entry point gives the same fit.
    let r = fit_aft(
        &TIME,
        &[X1.to_vec(), X2.to_vec()],
        &EVENT,
        &AftOptions {
            dist,
            ..Default::default()
        },
    )
    .unwrap();
    assert_eq!(r.core.coefficients[0], f.coefficients()[0]);
    assert_eq!(r.core.scale, f.scale());
}

#[test]
fn aft_weibull_matches_survreg() {
    aft_check(
        AftDistribution::Weibull,
        AFT_WEIBULL_COEF,
        AFT_WEIBULL_SCALE,
        AFT_WEIBULL_LL,
        &AFT_WEIBULL_SE,
        AFT_WEIBULL_Q,
    );
}

#[test]
fn aft_lognormal_matches_survreg() {
    aft_check(
        AftDistribution::LogNormal,
        AFT_LOGNORMAL_COEF,
        AFT_LOGNORMAL_SCALE,
        AFT_LOGNORMAL_LL,
        &AFT_LOGNORMAL_SE,
        AFT_LOGNORMAL_Q,
    );
}

#[test]
fn aft_loglogistic_matches_survreg() {
    aft_check(
        AftDistribution::LogLogistic,
        AFT_LOGLOGISTIC_COEF,
        AFT_LOGLOGISTIC_SCALE,
        AFT_LOGLOGISTIC_LL,
        &AFT_LOGLOGISTIC_SE,
        AFT_LOGLOGISTIC_Q,
    );
}

#[test]
fn aft_exponential_matches_survreg() {
    aft_check(
        AftDistribution::Exponential,
        AFT_EXPONENTIAL_COEF,
        AFT_EXPONENTIAL_SCALE,
        AFT_EXPONENTIAL_LL,
        &AFT_EXPONENTIAL_SE,
        AFT_EXPONENTIAL_Q,
    );
}

// #54: Poisson standard errors use dispersion 1 (R `glm(family = poisson)`), even
// on overdispersed data; the Pearson (quasi-Poisson) scale is opt-in.
#[test]
fn overdispersed_poisson_uses_dispersion_one() {
    let f = fit(PenalizedGlmFamily::poisson(), &Y_NB);
    check_glm(
        &f,
        POIS_OVER_COEF,
        POIS_OVER_SE,
        POIS_OVER_DEV,
        POIS_OVER_LL_AIC,
        "overdispersed poisson",
    );
    assert_eq!(f.dispersion(), 1.0);
}

#[test]
fn poisson_estimate_dispersion_matches_quasipoisson() {
    let f = PenalizedGlmRegressor::builder()
        .family(PenalizedGlmFamily::poisson())
        .estimate_dispersion(true)
        .compute_inference(true)
        .tolerance(1e-10)
        .build()
        .fit(&design(), &col(&Y_NB))
        .unwrap();
    rel_close(
        f.dispersion(),
        QPOIS_OVER_DISP,
        1e-7,
        "quasipoisson dispersion",
    );
    for j in 0..2 {
        rel_close(
            f.std_errors().unwrap()[j],
            QPOIS_OVER_SE[j + 1],
            1e-5,
            "quasipoisson se",
        );
    }
    // Same through the column-major entry point.
    let x = vec![X1.to_vec(), X2.to_vec()];
    let r = fit_poisson(
        &Y_NB,
        &x,
        &PoissonOptions {
            compute_inference: true,
            tolerance: 1e-10,
            estimate_dispersion: true,
            ..Default::default()
        },
    )
    .unwrap();
    let inf = r.inference.unwrap();
    rel_close(
        inf.std_errors[0],
        QPOIS_OVER_SE[1],
        1e-5,
        "fit_poisson quasipoisson se",
    );
}

// #55: Gamma logLik / AIC at dispersion deviance / n, as R's logLik.glm.
#[test]
fn gamma_log_likelihood_uses_deviance_over_n() {
    let f = fit(PenalizedGlmFamily::gamma(), &Y_GAMMA);
    rel_close(f.log_likelihood(), GAMMA_LL_AIC[0], 1e-9, "gamma logLik");
    rel_close(f.aic(), GAMMA_LL_AIC[1], 1e-9, "gamma AIC");
    // BIC = AIC - 2k + k log(n) with k = rank + 1 = 4.
    let bic = GAMMA_LL_AIC[1] - 8.0 + 4.0 * 60f64.ln();
    rel_close(f.bic(), bic, 1e-9, "gamma BIC");
}

// #56: null deviance as R's glm defines it.
#[test]
fn null_deviance_follows_r_with_offset_and_without_intercept() {
    let cases = [
        (
            PenalizedGlmFamily::poisson(),
            &Y_POIS,
            false,
            false,
            POIS_NOINT_COEF,
            POIS_NOINT_SE,
            POIS_NOINT_DEV,
            POIS_NOINT_LL_AIC,
            "poisson no intercept",
        ),
        (
            PenalizedGlmFamily::poisson(),
            &Y_POIS,
            false,
            true,
            POIS_NOINT_OFF_COEF,
            POIS_NOINT_OFF_SE,
            POIS_NOINT_OFF_DEV,
            POIS_NOINT_OFF_LL_AIC,
            "poisson no intercept + offset",
        ),
    ];
    for (fam, y, int, off, coef, se, dev, ll, what) in cases {
        check_glm(&fit_with(fam, y, int, off), coef, se, dev, ll, what);
    }
    let cases = [
        (
            PenalizedGlmFamily::poisson(),
            &Y_POIS,
            POIS_OFF_COEF,
            POIS_OFF_SE,
            POIS_OFF_DEV,
            POIS_OFF_LL_AIC,
            "poisson offset",
        ),
        (
            PenalizedGlmFamily::binomial(),
            &Y_BIN,
            BIN_OFF_COEF,
            BIN_OFF_SE,
            BIN_OFF_DEV,
            BIN_OFF_LL_AIC,
            "binomial offset",
        ),
        (
            PenalizedGlmFamily::gamma(),
            &Y_GAMMA,
            GAMMA_OFF_COEF,
            GAMMA_OFF_SE,
            GAMMA_OFF_DEV,
            GAMMA_OFF_LL_AIC,
            "gamma offset",
        ),
    ];
    for (fam, y, coef, se, dev, ll, what) in cases {
        let f = fit_with(fam, y, true, true);
        check_glm(&f, coef, se, dev, ll, what);
        rel_close(f.pseudo_r_squared(), 1.0 - dev[0] / dev[1], 1e-9, what);
    }
}
