//! GLMM validation against R `lme4` — random intercept, random slopes, crossed
//! and nested factors; fixed effects, standard errors, variance components,
//! per-group BLUPs, correlations and log-likelihood; the ML path, unbalanced
//! panels, a boundary (singular) fit, a no-intercept model, and determinism.
//!
//! Reference values are generated by `tests/r_scripts/generate_glmm_validation.R`
//! and embedded into `tests/fixtures/glmm_validation.rs`. Gaussian scenarios use
//! `lmer` (REML or ML); the Poisson and binomial scenarios use `glmer(nAGQ = 0)`,
//! which is the penalized-conditional-mode Laplace estimator the Rust solver
//! implements. To regenerate:
//!
//! ```bash
//! Rscript tests/r_scripts/generate_glmm_validation.R \
//!     > tests/fixtures/glmm_validation.rs
//! ```

#![allow(dead_code)]
// Fixture data occasionally contains a value near a math constant (e.g. a
// sample ≈ 1.1284 ≈ FRAC_2_SQRT_PI); it is data, not an intended constant.
#![allow(clippy::approx_constant)]

use anofox_regression::solvers::GlmmRegressor;
use faer::{Col, Mat};

include!("fixtures/glmm_validation.rs");

// The Gaussian LMM is solved in closed form per θ and matches lme4 to many
// digits; the small tolerance covers the golden-section resolution on θ.
const LMM_TOL: f64 = 2e-3;
// The GLMM Laplace (nAGQ=0) matches glmer(nAGQ=0); the looser tolerance covers
// the PIRLS convergence threshold and golden-section resolution.
const GLMM_TOL: f64 = 1e-2;

#[test]
fn lmm_univariate_matches_lme4() {
    let n = X_LMM_A.len();
    let x = Mat::from_fn(n, 1, |i, _| X_LMM_A[i]);
    let y = Col::from_fn(n, |i| Y_LMM_A[i]);

    let fit = GlmmRegressor::gaussian()
        .with_intercept(true)
        .reml(true)
        .build()
        .fit(&x, &y, &G_LMM_A)
        .expect("LMM fit failed");

    assert!((fit.intercept().unwrap() - LMM_A_INTERCEPT).abs() < LMM_TOL);
    assert!((fit.slopes()[0] - LMM_A_SLOPE).abs() < LMM_TOL);
    assert!((fit.sigma() - LMM_A_SIGMA).abs() < LMM_TOL);
    assert!((fit.sd_random() - LMM_A_SD_RANDOM).abs() < LMM_TOL);
    // deviance() is −2·logLik.
    assert!((fit.log_likelihood() - LMM_A_LOGLIK).abs() < 1e-2);

    // Fixed-effect standard errors vs sqrt(diag(vcov(m))).
    assert!(
        (fit.std_errors()[0] - LMM_A_SE_INTERCEPT).abs() < LMM_TOL,
        "se_intercept {} vs {LMM_A_SE_INTERCEPT}",
        fit.std_errors()[0]
    );
    assert!(
        (fit.std_errors()[1] - LMM_A_SE_SLOPE).abs() < LMM_TOL,
        "se_slope {} vs {LMM_A_SE_SLOPE}",
        fit.std_errors()[1]
    );

    for (j, &expected) in LMM_A_RANEF.iter().enumerate() {
        assert!(
            (fit.random_effects()[j] - expected).abs() < 5e-3,
            "ranef[{j}] = {} vs {expected}",
            fit.random_effects()[j]
        );
    }

    // Population-level prediction Xβ vs lme4 predict(re.form = NA).
    let pred = fit.predict_fixed(&x);
    for (i, &expected) in LMM_A_PREDFIXED.iter().enumerate() {
        assert!(
            (pred[i] - expected).abs() < LMM_TOL,
            "predict_fixed[{i}] = {} vs {expected}",
            pred[i]
        );
    }
}

#[test]
fn lmm_multivariate_matches_lme4() {
    let n = X1_LMM_B.len();
    let x = Mat::from_fn(n, 2, |i, k| if k == 0 { X1_LMM_B[i] } else { X2_LMM_B[i] });
    let y = Col::from_fn(n, |i| Y_LMM_B[i]);

    let fit = GlmmRegressor::gaussian()
        .with_intercept(true)
        .reml(true)
        .build()
        .fit(&x, &y, &G_LMM_B)
        .expect("LMM fit failed");

    assert!((fit.intercept().unwrap() - LMM_B_INTERCEPT).abs() < LMM_TOL);
    assert!((fit.slopes()[0] - LMM_B_SLOPE1).abs() < LMM_TOL);
    assert!((fit.slopes()[1] - LMM_B_SLOPE2).abs() < LMM_TOL);
    assert!((fit.sigma() - LMM_B_SIGMA).abs() < LMM_TOL);
    assert!((fit.sd_random() - LMM_B_SD_RANDOM).abs() < LMM_TOL);
}

#[test]
fn lmm_random_slope_matches_lme4() {
    // y ~ x + (x | g): random intercept + random slope with unstructured 2×2 Σ.
    let n = X_SLOPE_E.len();
    let x = Mat::from_fn(n, 1, |i, _| X_SLOPE_E[i]);
    let y = Col::from_fn(n, |i| Y_SLOPE_E[i]);

    let fit = GlmmRegressor::gaussian()
        .with_intercept(true)
        .random_slopes(vec![0])
        .reml(true)
        .tolerance(1e-9)
        .build()
        .fit(&x, &y, &G_SLOPE_E)
        .expect("random-slope LMM fit failed");

    assert_eq!(fit.n_random_effects(), 2);
    assert!((fit.intercept().unwrap() - SLOPE_E_INTERCEPT).abs() < LMM_TOL);
    assert!((fit.slopes()[0] - SLOPE_E_SLOPE).abs() < LMM_TOL);
    assert!((fit.sigma() - SLOPE_E_SIGMA).abs() < LMM_TOL);

    let sd = fit.random_sd();
    assert!(
        (sd[0] - SLOPE_E_SD_INTERCEPT).abs() < LMM_TOL,
        "sd_intercept {} vs {SLOPE_E_SD_INTERCEPT}",
        sd[0]
    );
    assert!(
        (sd[1] - SLOPE_E_SD_SLOPE).abs() < LMM_TOL,
        "sd_slope {} vs {SLOPE_E_SD_SLOPE}",
        sd[1]
    );
    let corr = fit.random_corr();
    assert!(
        (corr[0][1] - SLOPE_E_CORR).abs() < 5e-3,
        "corr {} vs {SLOPE_E_CORR}",
        corr[0][1]
    );

    assert!((fit.std_errors()[0] - SLOPE_E_SE_INTERCEPT).abs() < LMM_TOL);
    assert!((fit.std_errors()[1] - SLOPE_E_SE_SLOPE).abs() < LMM_TOL);

    // Per-group random intercepts and slopes vs ranef(m)$g[, 1:2].
    let re = fit.random_effects_matrix();
    for (j, (&ri, &sl)) in SLOPE_E_RANEF_INT
        .iter()
        .zip(SLOPE_E_RANEF_SLOPE.iter())
        .enumerate()
    {
        assert!(
            (re[j][0] - ri).abs() < 5e-3,
            "ranef_int[{j}] {} vs {ri}",
            re[j][0]
        );
        assert!(
            (re[j][1] - sl).abs() < 5e-3,
            "ranef_slope[{j}] {} vs {sl}",
            re[j][1]
        );
    }
}

#[test]
fn lmm_crossed_factors_match_lme4() {
    // y ~ x + (1|a) + (1|b): two crossed random-intercept factors.
    let n = X_CROSS_F.len();
    let x = Mat::from_fn(n, 1, |i, _| X_CROSS_F[i]);
    let y = Col::from_fn(n, |i| Y_CROSS_F[i]);

    let fit = GlmmRegressor::gaussian()
        .with_intercept(true)
        .reml(true)
        .tolerance(1e-9)
        .build()
        .fit_crossed(&x, &y, &[&A_CROSS_F, &B_CROSS_F])
        .expect("crossed LMM fit failed");

    assert_eq!(fit.n_factors(), 2);
    assert!((fit.intercept().unwrap() - CROSS_F_INTERCEPT).abs() < LMM_TOL);
    assert!((fit.slopes()[0] - CROSS_F_SLOPE).abs() < LMM_TOL);
    assert!((fit.sigma() - CROSS_F_SIGMA).abs() < LMM_TOL);
    assert!(
        (fit.factors()[0].sd - CROSS_F_SD_A).abs() < LMM_TOL,
        "sd_a {} vs {CROSS_F_SD_A}",
        fit.factors()[0].sd
    );
    assert!(
        (fit.factors()[1].sd - CROSS_F_SD_B).abs() < LMM_TOL,
        "sd_b {} vs {CROSS_F_SD_B}",
        fit.factors()[1].sd
    );
    assert!((fit.log_likelihood() - CROSS_F_LOGLIK).abs() < 1e-2);
    assert!((fit.std_errors()[0] - CROSS_F_SE_INTERCEPT).abs() < LMM_TOL);
    assert!((fit.std_errors()[1] - CROSS_F_SE_SLOPE).abs() < LMM_TOL);

    // Per-factor BLUPs vs ranef(m)$a and ranef(m)$b.
    for (l, &e) in CROSS_F_RANEF_A.iter().enumerate() {
        assert!((fit.factors()[0].blups[l] - e).abs() < 5e-3, "ranef_a[{l}]");
    }
    for (l, &e) in CROSS_F_RANEF_B.iter().enumerate() {
        assert!((fit.factors()[1].blups[l] - e).abs() < 5e-3, "ranef_b[{l}]");
    }
}

#[test]
fn lmm_nested_factors_match_lme4() {
    // y ~ x + (1|a/b) expressed as crossed (1|a) + (1|a:b).
    let n = X_NEST_G.len();
    let x = Mat::from_fn(n, 1, |i, _| X_NEST_G[i]);
    let y = Col::from_fn(n, |i| Y_NEST_G[i]);

    let fit = GlmmRegressor::gaussian()
        .with_intercept(true)
        .reml(true)
        .tolerance(1e-9)
        .build()
        .fit_crossed(&x, &y, &[&A_NEST_G, &AB_NEST_G])
        .expect("nested LMM fit failed");

    assert_eq!(fit.n_factors(), 2);
    assert!((fit.intercept().unwrap() - NEST_G_INTERCEPT).abs() < LMM_TOL);
    assert!((fit.slopes()[0] - NEST_G_SLOPE).abs() < LMM_TOL);
    assert!((fit.sigma() - NEST_G_SIGMA).abs() < LMM_TOL);
    // Factor 0 is `a`, factor 1 is the nested `a:b`.
    assert!(
        (fit.factors()[0].sd - NEST_G_SD_A).abs() < LMM_TOL,
        "sd_a {} vs {NEST_G_SD_A}",
        fit.factors()[0].sd
    );
    assert!(
        (fit.factors()[1].sd - NEST_G_SD_AB).abs() < LMM_TOL,
        "sd_ab {} vs {NEST_G_SD_AB}",
        fit.factors()[1].sd
    );
    assert!((fit.std_errors()[0] - NEST_G_SE_INTERCEPT).abs() < LMM_TOL);
    assert!((fit.std_errors()[1] - NEST_G_SE_SLOPE).abs() < LMM_TOL);

    for (l, &e) in NEST_G_RANEF_A.iter().enumerate() {
        assert!((fit.factors()[0].blups[l] - e).abs() < 5e-3, "ranef_a[{l}]");
    }
    for (l, &e) in NEST_G_RANEF_AB.iter().enumerate() {
        assert!(
            (fit.factors()[1].blups[l] - e).abs() < 5e-3,
            "ranef_ab[{l}]"
        );
    }
}

#[test]
fn poisson_glmm_matches_glmer_nagq0() {
    let n = X_POIS_C.len();
    let x = Mat::from_fn(n, 1, |i, _| X_POIS_C[i]);
    let y = Col::from_fn(n, |i| Y_POIS_C[i]);

    let fit = GlmmRegressor::poisson()
        .with_intercept(true)
        .build()
        .fit(&x, &y, &G_POIS_C)
        .expect("Poisson GLMM fit failed");

    assert!(fit.converged(), "PIRLS should converge");
    assert!(
        (fit.intercept().unwrap() - POIS_C_INTERCEPT).abs() < GLMM_TOL,
        "intercept {} vs {POIS_C_INTERCEPT}",
        fit.intercept().unwrap()
    );
    assert!((fit.slopes()[0] - POIS_C_SLOPE).abs() < GLMM_TOL);
    assert!((fit.sd_random() - POIS_C_SD_RANDOM).abs() < GLMM_TOL);

    // Fixed-effect SEs and random-intercept BLUPs vs glmer(nAGQ=0).
    assert!((fit.std_errors()[0] - POIS_C_SE_INTERCEPT).abs() < GLMM_TOL);
    assert!((fit.std_errors()[1] - POIS_C_SE_SLOPE).abs() < GLMM_TOL);
    for (j, &e) in POIS_C_RANEF.iter().enumerate() {
        assert!(
            (fit.random_effects()[j] - e).abs() < 2e-2,
            "poisson ranef[{j}] = {} vs {e}",
            fit.random_effects()[j]
        );
    }
}

#[test]
fn binomial_glmm_matches_glmer_nagq0() {
    let n = X_BIN_D.len();
    let x = Mat::from_fn(n, 1, |i, _| X_BIN_D[i]);
    let y = Col::from_fn(n, |i| Y_BIN_D[i]);

    let fit = GlmmRegressor::binomial()
        .with_intercept(true)
        .build()
        .fit(&x, &y, &G_BIN_D)
        .expect("Binomial GLMM fit failed");

    assert!(fit.converged(), "PIRLS should converge");
    assert!(
        (fit.intercept().unwrap() - BIN_D_INTERCEPT).abs() < GLMM_TOL,
        "intercept {} vs {BIN_D_INTERCEPT}",
        fit.intercept().unwrap()
    );
    assert!((fit.slopes()[0] - BIN_D_SLOPE).abs() < GLMM_TOL);
    assert!((fit.sd_random() - BIN_D_SD_RANDOM).abs() < GLMM_TOL);

    // Fixed-effect SEs and random-intercept BLUPs vs glmer(nAGQ=0).
    assert!((fit.std_errors()[0] - BIN_D_SE_INTERCEPT).abs() < GLMM_TOL);
    assert!((fit.std_errors()[1] - BIN_D_SE_SLOPE).abs() < GLMM_TOL);
    for (j, &e) in BIN_D_RANEF.iter().enumerate() {
        assert!(
            (fit.random_effects()[j] - e).abs() < 3e-2,
            "binomial ranef[{j}] = {} vs {e}",
            fit.random_effects()[j]
        );
    }
}

#[test]
fn poisson_glmm_multi_covariate_matches_glmer() {
    // Two fixed covariates + random intercept — exercises p > 2 in the GLMM path.
    let n = X1_POISM_M.len();
    let x = Mat::from_fn(
        n,
        2,
        |i, k| if k == 0 { X1_POISM_M[i] } else { X2_POISM_M[i] },
    );
    let y = Col::from_fn(n, |i| Y_POISM_M[i]);

    let fit = GlmmRegressor::poisson()
        .with_intercept(true)
        .build()
        .fit(&x, &y, &G_POISM_M)
        .expect("multi-covariate Poisson GLMM fit failed");

    assert!(fit.converged());
    assert!((fit.intercept().unwrap() - POISM_M_INTERCEPT).abs() < GLMM_TOL);
    assert!((fit.slopes()[0] - POISM_M_SLOPE1).abs() < GLMM_TOL);
    assert!((fit.slopes()[1] - POISM_M_SLOPE2).abs() < GLMM_TOL);
    assert!((fit.sd_random() - POISM_M_SD_RANDOM).abs() < GLMM_TOL);
    assert!((fit.std_errors()[0] - POISM_M_SE_INTERCEPT).abs() < GLMM_TOL);
    assert!((fit.std_errors()[1] - POISM_M_SE_SLOPE1).abs() < GLMM_TOL);
    assert!((fit.std_errors()[2] - POISM_M_SE_SLOPE2).abs() < GLMM_TOL);
}

#[test]
fn lmm_ml_path_matches_lme4() {
    // REML = FALSE: validates the ML deviance / variance components.
    let n = X_ML_H.len();
    let x = Mat::from_fn(n, 1, |i, _| X_ML_H[i]);
    let y = Col::from_fn(n, |i| Y_ML_H[i]);

    let fit = GlmmRegressor::gaussian()
        .with_intercept(true)
        .reml(false)
        .tolerance(1e-9)
        .build()
        .fit(&x, &y, &G_ML_H)
        .expect("ML LMM fit failed");

    assert!(!fit.is_reml());
    assert!((fit.intercept().unwrap() - ML_H_INTERCEPT).abs() < LMM_TOL);
    assert!((fit.slopes()[0] - ML_H_SLOPE).abs() < LMM_TOL);
    assert!((fit.sigma() - ML_H_SIGMA).abs() < LMM_TOL);
    assert!((fit.sd_random() - ML_H_SD_RANDOM).abs() < LMM_TOL);
    assert!((fit.log_likelihood() - ML_H_LOGLIK).abs() < 1e-2);
}

#[test]
fn lmm_unbalanced_matches_lme4() {
    // Unequal group sizes (2..14 observations).
    let n = X_UNBAL_I.len();
    let x = Mat::from_fn(n, 1, |i, _| X_UNBAL_I[i]);
    let y = Col::from_fn(n, |i| Y_UNBAL_I[i]);

    let fit = GlmmRegressor::gaussian()
        .with_intercept(true)
        .reml(true)
        .tolerance(1e-9)
        .build()
        .fit(&x, &y, &G_UNBAL_I)
        .expect("unbalanced LMM fit failed");

    assert!((fit.intercept().unwrap() - UNBAL_I_INTERCEPT).abs() < LMM_TOL);
    assert!((fit.slopes()[0] - UNBAL_I_SLOPE).abs() < LMM_TOL);
    assert!((fit.sigma() - UNBAL_I_SIGMA).abs() < LMM_TOL);
    assert!((fit.sd_random() - UNBAL_I_SD_RANDOM).abs() < LMM_TOL);
    assert!((fit.std_errors()[0] - UNBAL_I_SE_INTERCEPT).abs() < LMM_TOL);
    assert!((fit.std_errors()[1] - UNBAL_I_SE_SLOPE).abs() < LMM_TOL);
}

#[test]
fn lmm_boundary_singular_fit() {
    // No true between-group variance ⇒ lme4 reports a singular fit (sd ≈ 0).
    // The solver must drive θ → 0 and collapse to the OLS fit.
    let n = X_BND_J.len();
    let x = Mat::from_fn(n, 1, |i, _| X_BND_J[i]);
    let y = Col::from_fn(n, |i| Y_BND_J[i]);

    let fit = GlmmRegressor::gaussian()
        .with_intercept(true)
        .reml(true)
        .tolerance(1e-9)
        .build()
        .fit(&x, &y, &G_BND_J)
        .expect("boundary LMM fit failed");

    // lme4's sd_random is 0 here; ours should be essentially zero.
    assert!(
        fit.sd_random() < 0.05,
        "sd_random should collapse to ~0, got {}",
        fit.sd_random()
    );
    assert!((fit.sd_random() - BND_J_SD_RANDOM).abs() < 0.05);
    // Fixed effects and residual scale should match lme4's (OLS) fit.
    assert!((fit.intercept().unwrap() - BND_J_INTERCEPT).abs() < 5e-3);
    assert!((fit.slopes()[0] - BND_J_SLOPE).abs() < 5e-3);
    assert!((fit.sigma() - BND_J_SIGMA).abs() < 1e-2);
}

#[test]
fn lmm_no_intercept_matches_lme4() {
    // y ~ 0 + x + (1|g): fixed slope only, random intercept retained.
    let n = X_NOINT_K.len();
    let x = Mat::from_fn(n, 1, |i, _| X_NOINT_K[i]);
    let y = Col::from_fn(n, |i| Y_NOINT_K[i]);

    let fit = GlmmRegressor::gaussian()
        .with_intercept(false)
        .reml(true)
        .tolerance(1e-9)
        .build()
        .fit(&x, &y, &G_NOINT_K)
        .expect("no-intercept LMM fit failed");

    assert!(fit.intercept().is_none());
    assert!((fit.slopes()[0] - NOINT_K_SLOPE).abs() < LMM_TOL);
    assert!((fit.sigma() - NOINT_K_SIGMA).abs() < LMM_TOL);
    assert!((fit.sd_random() - NOINT_K_SD_RANDOM).abs() < LMM_TOL);
    assert!((fit.std_errors()[0] - NOINT_K_SE_SLOPE).abs() < LMM_TOL);
}

#[test]
fn glmm_fits_are_deterministic() {
    // Same input ⇒ bitwise-identical output (no RNG in the solver).
    let n = X_LMM_A.len();
    let x = Mat::from_fn(n, 1, |i, _| X_LMM_A[i]);
    let y = Col::from_fn(n, |i| Y_LMM_A[i]);
    let build = || {
        GlmmRegressor::gaussian()
            .with_intercept(true)
            .build()
            .fit(&x, &y, &G_LMM_A)
            .unwrap()
    };
    let a = build();
    let b = build();
    assert_eq!(a.fixed_effects(), b.fixed_effects());
    assert_eq!(a.sd_random().to_bits(), b.sd_random().to_bits());
    assert_eq!(a.deviance().to_bits(), b.deviance().to_bits());
}
