#!/usr/bin/env Rscript
# =============================================================================
# GLMM families / offset / crossed random slopes validation data (issue #29).
#
# Emits a Rust fixture of `const` arrays for `GlmmRegressor`. All GLMMs use the
# penalized-conditional-mode Laplace estimator, glmer's `nAGQ = 0`:
#   * H  negative binomial, θ estimated   -> lme4::glmer.nb(nAGQ = 0)
#   * I  negative binomial, θ = 2 fixed   -> glmer(family = MASS::negative.binomial(2))
#   * J  Gamma(log)                       -> glmer(family = Gamma(link = "log"))
#   * K  Tweedie p = 1.5 (log)            -> glmer with statmod::tweedie(1.5, 0),
#        its `aic` set to the Tweedie series log-density (tweedie::dtweedie) at
#        dispersion deviance/n (+2), mirroring R's Gamma()$aic. glmmTMB is not
#        used: it integrates the random effects with an ML dispersion, a
#        different estimator.
#   * L  Poisson with offset(log(exposure))
#   * M  Gaussian LMM with an offset      -> lmer(REML = TRUE)
#   * N  Gaussian (x | a) + (1 | b)       -> lmer(REML = TRUE)
#   * O  Poisson  (x | a) + (1 | b)       -> glmer(poisson, nAGQ = 0)
#   * P  Gamma    (1 | a) + (1 | b)       -> glmer(Gamma(log), nAGQ = 0)
#
# Regenerate with:
#   Rscript tests/r_scripts/generate_glmm_families_validation.R \
#       > tests/fixtures/glmm_families_validation.rs
# =============================================================================

suppressMessages({
  library(lme4)
  library(MASS)
  library(statmod)
  library(tweedie)
})

fmt_vec <- function(name, v, ty = "f64") {
  cat(sprintf("const %s: [%s; %d] = [", name, ty, length(v)))
  if (ty == "usize") {
    cat(paste(sprintf("%d", v), collapse = ", "))
  } else {
    cat(paste(sprintf("%.10f", v), collapse = ", "))
  }
  cat("];\n")
}
fmt_num <- function(name, v) cat(sprintf("const %s: f64 = %.10f;\n", name, v))

cat("// =============================================================================\n")
cat("// GLMM families validation data — generated by\n")
cat("// tests/r_scripts/generate_glmm_families_validation.R\n")
cat(sprintf("// R version: %s ; lme4: %s ; tweedie: %s ; statmod: %s\n",
            R.version.string, as.character(packageVersion("lme4")),
            as.character(packageVersion("tweedie")),
            as.character(packageVersion("statmod"))))
cat("// All GLMMs: nAGQ = 0. Gaussian: lmer(REML = TRUE).\n")
cat("// =============================================================================\n\n")

set.seed(20291)

emit_glmm <- function(tag, m, g_name = "g") {
  fmt_vec(paste0(tag, "_FIXEF"), unname(fixef(m)))
  fmt_vec(paste0(tag, "_SE"), unname(sqrt(diag(as.matrix(vcov(m))))))
  fmt_num(paste0(tag, "_LOGLIK"), as.numeric(logLik(m)))
  fmt_num(paste0(tag, "_SIGMA"), sigma(m))
  vc <- as.data.frame(VarCorr(m))
  fmt_num(paste0(tag, "_SD_RE"), vc$sdcor[vc$grp == g_name & is.na(vc$var2)][1])
  fmt_vec(paste0(tag, "_BLUP"), ranef(m)[[g_name]][, 1])
}

# Common single-factor panel.
J <- 12; ni <- 15; n <- J * ni
g <- rep(1:J, each = ni)
x <- round(rnorm(n), 4)
b <- rnorm(J, 0, 0.5)
mu <- exp(0.5 + 0.3 * x + b[g])
cat("// Shared panel: 12 groups x 15 obs.\n")
fmt_vec("X", x)
fmt_vec("G", g - 1L, "usize")

# ------------------------------------------------------------------ H / I: NB
y_nb <- rnbinom(n, size = 3, mu = mu)
fmt_vec("Y_NB", y_nb)
d <- data.frame(y = y_nb, x = x, g = factor(g))
mH <- glmer.nb(y ~ x + (1 | g), data = d, nAGQ = 0)
cat("// H: glmer.nb(y ~ x + (1|g), nAGQ = 0) — theta estimated\n")
emit_glmm("NB_H", mH)
fmt_num("NB_H_THETA", getME(mH, "glmer.nb.theta"))
mI <- glmer(y ~ x + (1 | g), data = d, family = negative.binomial(2), nAGQ = 0)
cat("// I: glmer(negative.binomial(2), nAGQ = 0) — theta fixed\n")
emit_glmm("NB_I", mI)

# ------------------------------------------------------------------ J: Gamma
y_ga <- round(rgamma(n, shape = 2, scale = mu / 2), 6)
fmt_vec("Y_GA", y_ga)
d <- data.frame(y = y_ga, x = x, g = factor(g))
mJ <- glmer(y ~ x + (1 | g), data = d, family = Gamma(link = "log"), nAGQ = 0)
cat("// J: glmer(Gamma(log), nAGQ = 0)\n")
emit_glmm("GA_J", mJ)

# ---------------------------------------------------------------- K: Tweedie
p_tw <- 1.5
y_tw <- round(rtweedie(n, power = p_tw, mu = mu, phi = 1.2), 6)
fmt_vec("Y_TW", y_tw)
fam_tw <- statmod::tweedie(var.power = p_tw, link.power = 0)
fam_tw$aic <- function(y, n, mu, wt, dev) {
  disp <- dev / sum(wt)
  -2 * sum(log(dtweedie(y, power = p_tw, mu = mu, phi = disp)) * wt) + 2
}
d <- data.frame(y = y_tw, x = x, g = factor(g))
mK <- glmer(y ~ x + (1 | g), data = d, family = fam_tw, nAGQ = 0)
cat("// K: glmer(statmod::tweedie(1.5, link.power = 0), nAGQ = 0), Tweedie aic\n")
emit_glmm("TW_K", mK)

# ------------------------------------------------------- L: Poisson + offset
expo <- round(runif(n, 0.5, 3), 4)
y_po <- rpois(n, expo * mu)
fmt_vec("EXPO", expo)
fmt_vec("Y_PO_OFF", y_po)
d <- data.frame(y = y_po, x = x, g = factor(g), lo = log(expo))
mL <- glmer(y ~ x + (1 | g) + offset(lo), data = d, family = poisson, nAGQ = 0)
cat("// L: glmer(y ~ x + (1|g) + offset(log(expo)), poisson, nAGQ = 0)\n")
emit_glmm("PO_L", mL)

# ------------------------------------------------------- M: Gaussian + offset
off_m <- round(rnorm(n, 0, 1), 4)
y_m <- round(1 + 0.5 * x + b[g] + off_m + rnorm(n, 0, 0.6), 4)
fmt_vec("OFF_M", off_m)
fmt_vec("Y_M", y_m)
d <- data.frame(y = y_m, x = x, g = factor(g), o = off_m)
mM <- lmer(y ~ x + (1 | g) + offset(o), data = d, REML = TRUE)
cat("// M: lmer(y ~ x + (1|g) + offset(o), REML = TRUE)\n")
emit_glmm("LMM_M", mM)

# ------------------------------------------- N / O / P: crossed (+ slopes)
Ja <- 10; Jb <- 6; nc <- 240
a <- sample(rep(1:Ja, length.out = nc))
bb <- sample(rep(1:Jb, length.out = nc))
xc <- round(rnorm(nc), 4)
ra0 <- rnorm(Ja, 0, 0.6); ra1 <- rnorm(Ja, 0, 0.3); rb <- rnorm(Jb, 0, 0.4)
cat("// Crossed panel: a (10 levels, random intercept + slope on x), b (6 levels).\n")
fmt_vec("XC", xc)
fmt_vec("A", a - 1L, "usize")
fmt_vec("B", bb - 1L, "usize")

emit_crossed <- function(tag, m, slope = TRUE) {
  fmt_vec(paste0(tag, "_FIXEF"), unname(fixef(m)))
  fmt_vec(paste0(tag, "_SE"), unname(sqrt(diag(as.matrix(vcov(m))))))
  fmt_num(paste0(tag, "_LOGLIK"), as.numeric(logLik(m)))
  fmt_num(paste0(tag, "_SIGMA"), sigma(m))
  vc <- as.data.frame(VarCorr(m))
  va <- vc[vc$grp == "a", ]
  fmt_num(paste0(tag, "_SD_A0"), va$sdcor[va$var1 == "(Intercept)" & is.na(va$var2)])
  if (slope) {
    fmt_num(paste0(tag, "_SD_A1"), va$sdcor[va$var1 == "x" & is.na(va$var2)])
    fmt_num(paste0(tag, "_CORR_A"), va$sdcor[!is.na(va$var2)])
  }
  fmt_num(paste0(tag, "_SD_B"), vc$sdcor[vc$grp == "b"])
  fmt_vec(paste0(tag, "_BLUP_A0"), ranef(m)$a[, 1])
  if (slope) fmt_vec(paste0(tag, "_BLUP_A1"), ranef(m)$a[, 2])
  fmt_vec(paste0(tag, "_BLUP_B"), ranef(m)$b[, 1])
}

y_n <- round(2 + 0.7 * xc + ra0[a] + ra1[a] * xc + rb[bb] + rnorm(nc, 0, 0.5), 4)
fmt_vec("Y_N", y_n)
d <- data.frame(y = y_n, x = xc, a = factor(a), b = factor(bb))
mN <- lmer(y ~ x + (x | a) + (1 | b), data = d, REML = TRUE,
           control = lmerControl(calc.derivs = FALSE))
cat("// N: lmer(y ~ x + (x|a) + (1|b), REML = TRUE)\n")
emit_crossed("LMM_N", mN)

y_o <- rpois(nc, exp(0.8 + 0.4 * xc + ra0[a] + ra1[a] * xc + rb[bb]))
fmt_vec("Y_O", y_o)
d <- data.frame(y = y_o, x = xc, a = factor(a), b = factor(bb))
mO <- glmer(y ~ x + (x | a) + (1 | b), data = d, family = poisson, nAGQ = 0)
cat("// O: glmer(y ~ x + (x|a) + (1|b), poisson, nAGQ = 0)\n")
emit_crossed("PO_O", mO)

y_p <- round(rgamma(nc, shape = 3, scale = exp(0.8 + 0.4 * xc + ra0[a] + rb[bb]) / 3), 6)
fmt_vec("Y_P", y_p)
d <- data.frame(y = y_p, x = xc, a = factor(a), b = factor(bb))
mP <- glmer(y ~ x + (1 | a) + (1 | b), data = d, family = Gamma(link = "log"), nAGQ = 0)
cat("// P: glmer(y ~ x + (1|a) + (1|b), Gamma(log), nAGQ = 0)\n")
emit_crossed("GA_P", mP, slope = FALSE)
