#!/usr/bin/env Rscript
# Reference values for intercept inference, linear logLik/AIC/BIC and
# diagnostics::augment (issue #66, M1-A).
# Run from the crate root:
#   Rscript tests/r_scripts/generate_m1a_validation.R > tests/fixtures/m1a_validation.rs
suppressPackageStartupMessages({ library(MASS) })
# Converge tightly: R's default epsilon = 1e-8 on the deviance leaves the
# standard errors of slowly converging fits (probit) off in the 5th digit.
ctl <- glm.control(epsilon = 1e-14, maxit = 100)
have_broom <- requireNamespace("broom", quietly = TRUE)

fmt <- function(v) paste(sprintf("%.15e", v), collapse = ", ")
arr <- function(name, v) cat(sprintf("pub const %s: [f64; %d] = [%s];\n", name, length(v), fmt(v)))
num <- function(name, v) cat(sprintf("pub const %s: f64 = %s;\n", name, sprintf("%.15e", v)))

cat("// Generated by tests/r_scripts/generate_m1a_validation.R -- do not edit.\n")
cat(sprintf("// %s, MASS %s, broom %s\n", R.version.string, packageVersion("MASS"),
            if (have_broom) as.character(packageVersion("broom")) else "n/a"))
cat("#![allow(dead_code)]\n\n")

d <- mtcars
arr("MT_MPG", d$mpg); arr("MT_WT", d$wt); arr("MT_HP", d$hp)
arr("MT_VS", d$vs); arr("MT_CARB", d$carb); arr("MT_W", 1 / d$cyl)
wb <- warpbreaks
arr("WB_BREAKS", wb$breaks)
arr("WB_WOOLB", as.numeric(wb$wool == "B"))
arr("WB_TM", as.numeric(wb$tension == "M")); arr("WB_TH", as.numeric(wb$tension == "H"))

# Coefficient table, intercept first: estimate, se, statistic, p, ci lower, ci upper.
coef_table <- function(prefix, m, ci) {
  s <- coef(summary(m))
  arr(paste0(prefix, "_EST"), s[, 1]); arr(paste0(prefix, "_SE"), s[, 2])
  arr(paste0(prefix, "_STAT"), s[, 3]); arr(paste0(prefix, "_P"), s[, 4])
  arr(paste0(prefix, "_CI_LO"), ci[, 1]); arr(paste0(prefix, "_CI_HI"), ci[, 2])
}

aug <- function(prefix, m, glm = FALSE) {
  if (glm) {
    arr(paste0(prefix, "_FITTED"), fitted(m))
    arr(paste0(prefix, "_RESID_DEV"), residuals(m, type = "deviance"))
    arr(paste0(prefix, "_RESID_PEAR"), residuals(m, type = "pearson"))
    arr(paste0(prefix, "_RSTD_DEV"), rstandard(m, type = "deviance"))
    arr(paste0(prefix, "_RSTD_PEAR"), rstandard(m, type = "pearson"))
  } else {
    arr(paste0(prefix, "_FITTED"), fitted(m))
    arr(paste0(prefix, "_RESID"), residuals(m))
    arr(paste0(prefix, "_RSTD"), rstandard(m))
  }
  arr(paste0(prefix, "_RSTUD"), rstudent(m))
  arr(paste0(prefix, "_HAT"), hatvalues(m))
  arr(paste0(prefix, "_COOK"), cooks.distance(m))
  arr(paste0(prefix, "_DFFITS"), dffits(m))
  # influence.measures and broom::augment agree with the individual functions.
  im <- influence.measures(m)$infmat
  stopifnot(isTRUE(all.equal(unname(im[, "hat"]), unname(hatvalues(m)))))
  # (influence.measures' dffit ignores the fixed dispersion of binomial /
  # Poisson fits, unlike dffits.glm; compare it only where they coincide.)
  if (!glm || stats:::estDisp(family(m)))
    stopifnot(isTRUE(all.equal(unname(im[, "dffit"]), unname(dffits(m)))))
  stopifnot(isTRUE(all.equal(unname(im[, "cook.d"]), unname(cooks.distance(m)))))
  if (have_broom) {
    a <- broom::augment(m)
    stopifnot(isTRUE(all.equal(a$.hat, unname(hatvalues(m)))))
    stopifnot(isTRUE(all.equal(a$.cooksd, unname(cooks.distance(m)))))
    rs <- if (glm) rstandard(m, type = "deviance") else rstandard(m)
    stopifnot(isTRUE(all.equal(a$.std.resid, unname(rs))))
  }
}

ic <- function(prefix, m) {
  num(paste0(prefix, "_LOGLIK"), as.numeric(logLik(m)))
  num(paste0(prefix, "_AIC"), AIC(m)); num(paste0(prefix, "_BIC"), BIC(m))
  if (have_broom) {
    g <- broom::glance(m)
    stopifnot(isTRUE(all.equal(g$AIC, AIC(m))), isTRUE(all.equal(g$BIC, BIC(m))))
  }
}

cat("\n// OLS: lm(mpg ~ wt + hp, mtcars)\n")
ols <- lm(mpg ~ wt + hp, d)
coef_table("OLS", ols, confint(ols)); ic("OLS", ols); aug("OLS", ols)

cat("\n// OLS without intercept: lm(mpg ~ 0 + wt + hp, mtcars)\n")
ols0 <- lm(mpg ~ 0 + wt + hp, d); ic("OLS0", ols0)

cat("\n// WLS: lm(mpg ~ wt + hp, mtcars, weights = 1/cyl)\n")
wls <- lm(mpg ~ wt + hp, d, weights = 1 / cyl)
coef_table("WLS", wls, confint(wls)); ic("WLS", wls); aug("WLS", wls)

cat("\n// Binomial logit: glm(vs ~ mpg, binomial)\n")
bl <- glm(vs ~ mpg, binomial, d, control = ctl)
coef_table("BIN", bl, confint.default(bl)); aug("BIN", bl, TRUE)

cat("\n// Binomial probit: glm(vs ~ mpg, binomial(probit))\n")
bp <- glm(vs ~ mpg, binomial("probit"), d, control = ctl)
coef_table("PROBIT", bp, confint.default(bp))

cat("\n// Poisson: glm(carb ~ wt + hp, poisson)\n")
po <- glm(carb ~ wt + hp, poisson, d, control = ctl)
coef_table("POIS", po, confint.default(po)); aug("POIS", po, TRUE)

cat("\n// Gamma log: glm(mpg ~ wt + hp, Gamma(log))\n")
ga <- glm(mpg ~ wt + hp, Gamma("log"), d, control = ctl)
s <- summary(ga)
coef_table("GAMMA", ga, coef(ga) + outer(sqrt(diag(vcov(ga))), qt(c(0.025, 0.975), ga$df.residual)))
num("GAMMA_DISPERSION", s$dispersion)
aug("GAMMA", ga, TRUE)

cat("\n// Negative binomial: MASS::glm.nb(breaks ~ wool + tension, warpbreaks)\n")
nb <- glm.nb(breaks ~ wool + tension, wb, control = ctl)
coef_table("NB", nb, confint.default(nb)); num("NB_THETA", nb$theta)
aug("NB", nb, TRUE)
