#!/usr/bin/env Rscript
# =============================================================================
# GLMM validation data generator.
#
# Emits a Rust fixture of `const` arrays for the GLMM solver (`GlmmRegressor`,
# Phases A and B — random intercept and random slopes). Reference fits come from
# lme4:
#   * Gaussian LMM  -> lme4::lmer(..., REML = TRUE)
#   * Poisson GLMM  -> lme4::glmer(..., family = poisson, nAGQ = 0)
#   * Binomial GLMM -> lme4::glmer(..., family = binomial, nAGQ = 0)
#   * Random slope  -> lme4::lmer(y ~ x + (x | g), REML = TRUE)
#
# The Rust solver reproduces the penalized-conditional-mode Laplace estimator,
# which corresponds to glmer's `nAGQ = 0`. The data arrays are emitted verbatim
# so the Rust tests fit exactly the same numbers.
#
# Regenerate with:
#   Rscript tests/r_scripts/generate_glmm_validation.R \
#       > tests/fixtures/glmm_validation.rs
# =============================================================================

suppressMessages(library(lme4))

fmt_vec <- function(name, v, ty = "f64") {
  cat(sprintf("const %s: [%s; %d] = [", name, ty, length(v)))
  if (ty == "usize") {
    cat(paste(sprintf("%d", v), collapse = ", "))
  } else {
    cat(paste(sprintf("%.10f", v), collapse = ", "))
  }
  cat("];\n")
}

cat("// =============================================================================\n")
cat("// GLMM validation data — generated by tests/r_scripts/generate_glmm_validation.R\n")
cat(sprintf("// R version: %s ; lme4: %s\n",
            R.version.string, as.character(packageVersion("lme4"))))
cat("// Gaussian: lmer(REML=TRUE); Poisson/Binomial: glmer(nAGQ=0).\n")
cat("// =============================================================================\n\n")

set.seed(42)

# ------------------------------------------------------------------ Scenario A
# Gaussian LMM, one covariate, random intercept over 8 groups.
{
  J <- 8; ni <- 10; n <- J * ni
  g <- rep(1:J, each = ni)
  x <- round(rnorm(n), 4)
  b <- rnorm(J, 0, 0.8)
  y <- round(1.0 + 0.5 * x + b[g] + rnorm(n, 0, 0.5), 4)
  m <- lmer(y ~ x + (1 | g), REML = TRUE,
            control = lmerControl(calc.derivs = FALSE))
  vc <- as.data.frame(VarCorr(m))
  re <- ranef(m)$g[, 1]
  cat("// Scenario A: Gaussian LMM, y ~ x + (1|g), REML\n")
  fmt_vec("X_LMM_A", x)
  fmt_vec("G_LMM_A", g - 1L, "usize")
  fmt_vec("Y_LMM_A", y)
  cat(sprintf("const LMM_A_INTERCEPT: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const LMM_A_SLOPE: f64 = %.10f;\n", fixef(m)[2]))
  cat(sprintf("const LMM_A_SIGMA: f64 = %.10f;\n", sigma(m)))
  cat(sprintf("const LMM_A_SD_RANDOM: f64 = %.10f;\n", vc$sdcor[1]))
  cat(sprintf("const LMM_A_LOGLIK: f64 = %.10f;\n", as.numeric(logLik(m))))
  se <- sqrt(diag(vcov(m)))
  cat(sprintf("const LMM_A_SE_INTERCEPT: f64 = %.10f;\n", se[1]))
  cat(sprintf("const LMM_A_SE_SLOPE: f64 = %.10f;\n", se[2]))
  fmt_vec("LMM_A_RANEF", re)
  # Population-level (marginal) prediction Xβ at the training rows, for
  # validating predict_fixed (random effects set to zero).
  fmt_vec("LMM_A_PREDFIXED", as.numeric(predict(m, re.form = NA)))
  cat("\n")
}

# ------------------------------------------------------------------ Scenario B
# Gaussian LMM, two covariates, random intercept over 6 groups.
{
  J <- 6; ni <- 12; n <- J * ni
  g <- rep(1:J, each = ni)
  x1 <- round(rnorm(n), 4)
  x2 <- round(rnorm(n), 4)
  b <- rnorm(J, 0, 1.2)
  y <- round(0.5 + 0.7 * x1 - 0.4 * x2 + b[g] + rnorm(n, 0, 0.6), 4)
  m <- lmer(y ~ x1 + x2 + (1 | g), REML = TRUE,
            control = lmerControl(calc.derivs = FALSE))
  vc <- as.data.frame(VarCorr(m))
  cat("// Scenario B: Gaussian LMM, y ~ x1 + x2 + (1|g), REML\n")
  fmt_vec("X1_LMM_B", x1)
  fmt_vec("X2_LMM_B", x2)
  fmt_vec("G_LMM_B", g - 1L, "usize")
  fmt_vec("Y_LMM_B", y)
  cat(sprintf("const LMM_B_INTERCEPT: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const LMM_B_SLOPE1: f64 = %.10f;\n", fixef(m)[2]))
  cat(sprintf("const LMM_B_SLOPE2: f64 = %.10f;\n", fixef(m)[3]))
  cat(sprintf("const LMM_B_SIGMA: f64 = %.10f;\n", sigma(m)))
  cat(sprintf("const LMM_B_SD_RANDOM: f64 = %.10f;\n", vc$sdcor[1]))
  cat("\n")
}

# ------------------------------------------------------------------ Scenario C
# Poisson GLMM, one covariate, random intercept over 8 groups.
{
  J <- 8; ni <- 10; n <- J * ni
  g <- rep(1:J, each = ni)
  x <- round(rnorm(n), 4)
  b <- rnorm(J, 0, 0.8)
  y <- rpois(n, exp(-0.2 + 0.4 * x + b[g]))
  m <- glmer(y ~ x + (1 | g), family = poisson, nAGQ = 0)
  vc <- as.data.frame(VarCorr(m))
  cat("// Scenario C: Poisson GLMM, y ~ x + (1|g), nAGQ=0\n")
  fmt_vec("X_POIS_C", x)
  fmt_vec("G_POIS_C", g - 1L, "usize")
  fmt_vec("Y_POIS_C", as.numeric(y))
  cat(sprintf("const POIS_C_INTERCEPT: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const POIS_C_SLOPE: f64 = %.10f;\n", fixef(m)[2]))
  cat(sprintf("const POIS_C_SD_RANDOM: f64 = %.10f;\n", vc$sdcor[1]))
  se <- sqrt(diag(vcov(m)))
  cat(sprintf("const POIS_C_SE_INTERCEPT: f64 = %.10f;\n", se[1]))
  cat(sprintf("const POIS_C_SE_SLOPE: f64 = %.10f;\n", se[2]))
  fmt_vec("POIS_C_RANEF", ranef(m)$g[, 1])
  cat("\n")
}

# ------------------------------------------------------------------ Scenario D
# Binomial GLMM, one covariate, random intercept over 10 groups.
{
  J <- 10; ni <- 12; n <- J * ni
  g <- rep(1:J, each = ni)
  x <- round(rnorm(n), 4)
  b <- rnorm(J, 0, 1.0)
  p <- plogis(-0.3 + 0.8 * x + b[g])
  y <- rbinom(n, 1, p)
  m <- glmer(y ~ x + (1 | g), family = binomial, nAGQ = 0)
  vc <- as.data.frame(VarCorr(m))
  cat("// Scenario D: Binomial GLMM, y ~ x + (1|g), nAGQ=0\n")
  fmt_vec("X_BIN_D", x)
  fmt_vec("G_BIN_D", g - 1L, "usize")
  fmt_vec("Y_BIN_D", as.numeric(y))
  cat(sprintf("const BIN_D_INTERCEPT: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const BIN_D_SLOPE: f64 = %.10f;\n", fixef(m)[2]))
  cat(sprintf("const BIN_D_SD_RANDOM: f64 = %.10f;\n", vc$sdcor[1]))
  se <- sqrt(diag(vcov(m)))
  cat(sprintf("const BIN_D_SE_INTERCEPT: f64 = %.10f;\n", se[1]))
  cat(sprintf("const BIN_D_SE_SLOPE: f64 = %.10f;\n", se[2]))
  fmt_vec("BIN_D_RANEF", ranef(m)$g[, 1])
  cat("\n")
}

# ------------------------------------------------------------------ Scenario E
# Gaussian LMM with a correlated random intercept + random slope, 10 groups.
{
  suppressMessages(library(MASS))
  J <- 10; ni <- 12; n <- J * ni
  g <- rep(1:J, each = ni)
  x <- round(rnorm(n), 4)
  S <- matrix(c(0.8^2, 0.3 * 0.8 * 0.5, 0.3 * 0.8 * 0.5, 0.5^2), 2, 2)
  bb <- mvrnorm(J, c(0, 0), S)
  y <- round(1.0 + 0.6 * x + bb[g, 1] + bb[g, 2] * x + rnorm(n, 0, 0.5), 4)
  m <- lmer(y ~ x + (x | g), REML = TRUE,
            control = lmerControl(calc.derivs = FALSE))
  vc <- as.data.frame(VarCorr(m))
  # vc rows: 1 = sd(Intercept), 2 = sd(x slope), 3 = corr(Intercept, x).
  cat("// Scenario E: Gaussian LMM with random slope, y ~ x + (x|g), REML\n")
  fmt_vec("X_SLOPE_E", x)
  fmt_vec("G_SLOPE_E", g - 1L, "usize")
  fmt_vec("Y_SLOPE_E", y)
  cat(sprintf("const SLOPE_E_INTERCEPT: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const SLOPE_E_SLOPE: f64 = %.10f;\n", fixef(m)[2]))
  cat(sprintf("const SLOPE_E_SIGMA: f64 = %.10f;\n", sigma(m)))
  cat(sprintf("const SLOPE_E_SD_INTERCEPT: f64 = %.10f;\n", vc$sdcor[1]))
  cat(sprintf("const SLOPE_E_SD_SLOPE: f64 = %.10f;\n", vc$sdcor[2]))
  cat(sprintf("const SLOPE_E_CORR: f64 = %.10f;\n", vc$sdcor[3]))
  se <- sqrt(diag(vcov(m)))
  cat(sprintf("const SLOPE_E_SE_INTERCEPT: f64 = %.10f;\n", se[1]))
  cat(sprintf("const SLOPE_E_SE_SLOPE: f64 = %.10f;\n", se[2]))
  fmt_vec("SLOPE_E_RANEF_INT", ranef(m)$g[, 1])
  fmt_vec("SLOPE_E_RANEF_SLOPE", ranef(m)$g[, 2])
  cat("\n")
}

# ------------------------------------------------------------------ Scenario F
# Crossed random intercepts: y ~ x + (1|a) + (1|b), a and b fully crossed.
{
  set.seed(11)
  na <- 6; nb <- 5; rp <- 4; n <- na * nb * rp
  a <- rep(1:na, each = nb * rp)
  b <- rep(rep(1:nb, each = rp), times = na)
  x <- round(rnorm(n), 4)
  ba <- rnorm(na, 0, 0.9); bb <- rnorm(nb, 0, 0.6)
  y <- round(1.0 + 0.5 * x + ba[a] + bb[b] + rnorm(n, 0, 0.5), 4)
  m <- lmer(y ~ x + (1 | a) + (1 | b), REML = TRUE,
            control = lmerControl(calc.derivs = FALSE))
  vc <- as.data.frame(VarCorr(m))
  # vc grp order is data-dependent; index by name.
  sd_a <- vc$sdcor[vc$grp == "a"]
  sd_b <- vc$sdcor[vc$grp == "b"]
  cat("// Scenario F: crossed random intercepts, y ~ x + (1|a) + (1|b), REML\n")
  fmt_vec("X_CROSS_F", x)
  fmt_vec("A_CROSS_F", a - 1L, "usize")
  fmt_vec("B_CROSS_F", b - 1L, "usize")
  fmt_vec("Y_CROSS_F", y)
  cat(sprintf("const CROSS_F_INTERCEPT: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const CROSS_F_SLOPE: f64 = %.10f;\n", fixef(m)[2]))
  cat(sprintf("const CROSS_F_SIGMA: f64 = %.10f;\n", sigma(m)))
  cat(sprintf("const CROSS_F_SD_A: f64 = %.10f;\n", sd_a))
  cat(sprintf("const CROSS_F_SD_B: f64 = %.10f;\n", sd_b))
  cat(sprintf("const CROSS_F_LOGLIK: f64 = %.10f;\n", as.numeric(logLik(m))))
  se <- sqrt(diag(vcov(m)))
  cat(sprintf("const CROSS_F_SE_INTERCEPT: f64 = %.10f;\n", se[1]))
  cat(sprintf("const CROSS_F_SE_SLOPE: f64 = %.10f;\n", se[2]))
  fmt_vec("CROSS_F_RANEF_A", ranef(m)$a[, 1])
  fmt_vec("CROSS_F_RANEF_B", ranef(m)$b[, 1])
  cat("\n")
}

# ------------------------------------------------------------------ Scenario G
# Nested random intercepts: y ~ x + (1|a/b)  ==  (1|a) + (1|a:b).
{
  set.seed(13)
  na <- 5; nb <- 4; rp <- 6; n <- na * nb * rp
  a <- rep(1:na, each = nb * rp)
  bwithin <- rep(rep(1:nb, each = rp), times = na)
  ab <- (a - 1) * nb + bwithin   # globally-unique nested id
  x <- round(rnorm(n), 4)
  ea <- rnorm(na, 0, 0.8); eab <- rnorm(na * nb, 0, 0.5)
  y <- round(0.5 + 0.4 * x + ea[a] + eab[ab] + rnorm(n, 0, 0.4), 4)
  m <- lmer(y ~ x + (1 | a) + (1 | ab), REML = TRUE,
            control = lmerControl(calc.derivs = FALSE))
  vc <- as.data.frame(VarCorr(m))
  sd_a <- vc$sdcor[vc$grp == "a"]
  sd_ab <- vc$sdcor[vc$grp == "ab"]
  cat("// Scenario G: nested random intercepts, y ~ x + (1|a/b) = (1|a)+(1|a:b), REML\n")
  fmt_vec("X_NEST_G", x)
  fmt_vec("A_NEST_G", a - 1L, "usize")
  fmt_vec("AB_NEST_G", ab - 1L, "usize")
  fmt_vec("Y_NEST_G", y)
  cat(sprintf("const NEST_G_INTERCEPT: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const NEST_G_SLOPE: f64 = %.10f;\n", fixef(m)[2]))
  cat(sprintf("const NEST_G_SIGMA: f64 = %.10f;\n", sigma(m)))
  cat(sprintf("const NEST_G_SD_A: f64 = %.10f;\n", sd_a))
  cat(sprintf("const NEST_G_SD_AB: f64 = %.10f;\n", sd_ab))
  se <- sqrt(diag(vcov(m)))
  cat(sprintf("const NEST_G_SE_INTERCEPT: f64 = %.10f;\n", se[1]))
  cat(sprintf("const NEST_G_SE_SLOPE: f64 = %.10f;\n", se[2]))
  fmt_vec("NEST_G_RANEF_A", ranef(m)$a[, 1])
  fmt_vec("NEST_G_RANEF_AB", ranef(m)$ab[, 1])
  cat("\n")
}

# ------------------------------------------------------------------ Scenario H
# Gaussian LMM fit by ML (REML = FALSE), one covariate — validates the ML path.
{
  set.seed(101)
  J <- 8; ni <- 10; n <- J * ni
  g <- rep(1:J, each = ni)
  x <- round(rnorm(n), 4)
  b <- rnorm(J, 0, 0.7)
  y <- round(0.8 + 0.6 * x + b[g] + rnorm(n, 0, 0.5), 4)
  m <- lmer(y ~ x + (1 | g), REML = FALSE,
            control = lmerControl(calc.derivs = FALSE))
  vc <- as.data.frame(VarCorr(m))
  cat("// Scenario H: Gaussian LMM by ML (REML=FALSE), y ~ x + (1|g)\n")
  fmt_vec("X_ML_H", x)
  fmt_vec("G_ML_H", g - 1L, "usize")
  fmt_vec("Y_ML_H", y)
  cat(sprintf("const ML_H_INTERCEPT: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const ML_H_SLOPE: f64 = %.10f;\n", fixef(m)[2]))
  cat(sprintf("const ML_H_SIGMA: f64 = %.10f;\n", sigma(m)))
  cat(sprintf("const ML_H_SD_RANDOM: f64 = %.10f;\n", vc$sdcor[1]))
  cat(sprintf("const ML_H_LOGLIK: f64 = %.10f;\n", as.numeric(logLik(m))))
  cat("\n")
}

# ------------------------------------------------------------------ Scenario I
# Unbalanced Gaussian LMM: groups of unequal size (2..14 observations).
{
  set.seed(102)
  sizes <- c(2, 3, 5, 8, 14, 4, 11, 6)
  J <- length(sizes); n <- sum(sizes)
  g <- rep(seq_len(J), times = sizes)
  x <- round(rnorm(n), 4)
  b <- rnorm(J, 0, 0.9)
  y <- round(1.2 - 0.5 * x + b[g] + rnorm(n, 0, 0.5), 4)
  m <- lmer(y ~ x + (1 | g), REML = TRUE,
            control = lmerControl(calc.derivs = FALSE))
  vc <- as.data.frame(VarCorr(m))
  se <- sqrt(diag(vcov(m)))
  cat("// Scenario I: unbalanced Gaussian LMM, unequal group sizes, y ~ x + (1|g)\n")
  fmt_vec("X_UNBAL_I", x)
  fmt_vec("G_UNBAL_I", g - 1L, "usize")
  fmt_vec("Y_UNBAL_I", y)
  cat(sprintf("const UNBAL_I_INTERCEPT: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const UNBAL_I_SLOPE: f64 = %.10f;\n", fixef(m)[2]))
  cat(sprintf("const UNBAL_I_SIGMA: f64 = %.10f;\n", sigma(m)))
  cat(sprintf("const UNBAL_I_SD_RANDOM: f64 = %.10f;\n", vc$sdcor[1]))
  cat(sprintf("const UNBAL_I_SE_INTERCEPT: f64 = %.10f;\n", se[1]))
  cat(sprintf("const UNBAL_I_SE_SLOPE: f64 = %.10f;\n", se[2]))
  cat("\n")
}

# ------------------------------------------------------------------ Scenario J
# Boundary case: no true between-group variance ⇒ lme4 gives a singular fit with
# sd_random ≈ 0. Validates the θ → 0 boundary of the profiled search.
{
  set.seed(103)
  J <- 8; ni <- 12; n <- J * ni
  g <- rep(1:J, each = ni)
  x <- round(rnorm(n), 4)
  y <- round(1.0 + 0.5 * x + rnorm(n, 0, 0.5), 4)   # no group effect
  m <- suppressMessages(lmer(y ~ x + (1 | g), REML = TRUE,
            control = lmerControl(calc.derivs = FALSE)))
  vc <- as.data.frame(VarCorr(m))
  cat("// Scenario J: boundary (singular) LMM, zero group variance, y ~ x + (1|g)\n")
  fmt_vec("X_BND_J", x)
  fmt_vec("G_BND_J", g - 1L, "usize")
  fmt_vec("Y_BND_J", y)
  cat(sprintf("const BND_J_INTERCEPT: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const BND_J_SLOPE: f64 = %.10f;\n", fixef(m)[2]))
  cat(sprintf("const BND_J_SIGMA: f64 = %.10f;\n", sigma(m)))
  cat(sprintf("const BND_J_SD_RANDOM: f64 = %.10f;\n", vc$sdcor[1]))
  cat("\n")
}

# ------------------------------------------------------------------ Scenario K
# No fixed intercept: y ~ 0 + x + (1|g). Validates with_intercept(false).
{
  set.seed(104)
  J <- 7; ni <- 12; n <- J * ni
  g <- rep(1:J, each = ni)
  x <- round(rnorm(n), 4)
  b <- rnorm(J, 0, 0.8)
  y <- round(0.9 * x + b[g] + rnorm(n, 0, 0.5), 4)
  m <- lmer(y ~ 0 + x + (1 | g), REML = TRUE,
            control = lmerControl(calc.derivs = FALSE))
  vc <- as.data.frame(VarCorr(m))
  se <- sqrt(diag(vcov(m)))
  cat("// Scenario K: no fixed intercept, y ~ 0 + x + (1|g), REML\n")
  fmt_vec("X_NOINT_K", x)
  fmt_vec("G_NOINT_K", g - 1L, "usize")
  fmt_vec("Y_NOINT_K", y)
  cat(sprintf("const NOINT_K_SLOPE: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const NOINT_K_SIGMA: f64 = %.10f;\n", sigma(m)))
  cat(sprintf("const NOINT_K_SD_RANDOM: f64 = %.10f;\n", vc$sdcor[1]))
  cat(sprintf("const NOINT_K_SE_SLOPE: f64 = %.10f;\n", se[1]))
  cat("\n")
}

# ------------------------------------------------------------------ Scenario M
# Multi-covariate Poisson GLMM: y ~ x1 + x2 + (1|g), nAGQ = 0.
{
  set.seed(105)
  J <- 8; ni <- 12; n <- J * ni
  g <- rep(1:J, each = ni)
  x1 <- round(rnorm(n), 4)
  x2 <- round(rnorm(n), 4)
  b <- rnorm(J, 0, 0.6)
  y <- rpois(n, exp(-0.1 + 0.3 * x1 - 0.25 * x2 + b[g]))
  m <- glmer(y ~ x1 + x2 + (1 | g), family = poisson, nAGQ = 0)
  vc <- as.data.frame(VarCorr(m))
  se <- sqrt(diag(vcov(m)))
  cat("// Scenario M: Poisson GLMM, two covariates, y ~ x1 + x2 + (1|g), nAGQ=0\n")
  fmt_vec("X1_POISM_M", x1)
  fmt_vec("X2_POISM_M", x2)
  fmt_vec("G_POISM_M", g - 1L, "usize")
  fmt_vec("Y_POISM_M", as.numeric(y))
  cat(sprintf("const POISM_M_INTERCEPT: f64 = %.10f;\n", fixef(m)[1]))
  cat(sprintf("const POISM_M_SLOPE1: f64 = %.10f;\n", fixef(m)[2]))
  cat(sprintf("const POISM_M_SLOPE2: f64 = %.10f;\n", fixef(m)[3]))
  cat(sprintf("const POISM_M_SD_RANDOM: f64 = %.10f;\n", vc$sdcor[1]))
  cat(sprintf("const POISM_M_SE_INTERCEPT: f64 = %.10f;\n", se[1]))
  cat(sprintf("const POISM_M_SE_SLOPE1: f64 = %.10f;\n", se[2]))
  cat(sprintf("const POISM_M_SE_SLOPE2: f64 = %.10f;\n", se[3]))
  cat("\n")
}
