# Generates tests/fixtures/penalized_glm_aft_reference.rs (issues #44, #45),
# the reference module of tests/r_validation_penalized_glm_aft.rs.
# Run: Rscript tests/r_scripts/penalized_glm_aft_reference.R > tests/fixtures/penalized_glm_aft_reference.rs
suppressPackageStartupMessages({ library(MASS); library(survival) })
set.seed(4445)
n <- 60
x1 <- round(rnorm(n), 4); x2 <- round(runif(n, -1, 1), 4)
expo <- round(runif(n, 0.5, 2), 4); off <- log(expo)
yp <- rpois(n, exp(0.3 + 0.5 * x1 - 0.4 * x2) * expo)
yb <- rbinom(n, 1, plogis(-0.2 + 0.9 * x1 + 0.6 * x2))
ynb <- rnbinom(n, mu = exp(1 + 0.4 * x1 - 0.3 * x2), size = 2)
yg <- round(rgamma(n, shape = 3, rate = 3 / exp(0.5 + 0.3 * x1 - 0.2 * x2)), 4)
tt <- round(rweibull(n, shape = 1.5, scale = exp(1 + 0.5 * x1 - 0.3 * x2)), 4)
cens <- round(runif(n, 0.5, 6), 4)
time <- pmin(tt, cens); ev <- as.numeric(tt <= cens)

num <- function(v) { s <- sprintf("%.17g", v); ifelse(grepl("[.eE]", s), s, paste0(s, ".0")) }
f <- function(v) paste0("[", paste(num(v), collapse = ", "), "]")
cat("//! R reference values for the penalized GLM engine and the AFT model.\n")
cat("//! GENERATED by tests/r_scripts/penalized_glm_aft_reference.R -- do not edit.\n")
cat("//! ", R.version.string, ", MASS ", as.character(packageVersion("MASS")),
    ", survival ", as.character(packageVersion("survival")), "\n\n", sep = "")
cat("#![allow(clippy::excessive_precision, clippy::approx_constant)]\n\n")
cat("pub const X1: [f64; 60] = ", f(x1), ";\n", sep = "")
cat("pub const X2: [f64; 60] = ", f(x2), ";\n", sep = "")
cat("pub const OFFSET: [f64; 60] = ", f(off), ";\n", sep = "")
cat("pub const Y_POIS: [f64; 60] = ", f(yp), ";\n", sep = "")
cat("pub const Y_BIN: [f64; 60] = ", f(yb), ";\n", sep = "")
cat("pub const Y_NB: [f64; 60] = ", f(ynb), ";\n", sep = "")
cat("pub const Y_GAMMA: [f64; 60] = ", f(yg), ";\n", sep = "")
cat("pub const TIME: [f64; 60] = ", f(time), ";\n", sep = "")
cat("pub const EVENT: [f64; 60] = ", f(ev), ";\n\n", sep = "")

ctl <- glm.control(epsilon = 1e-14, maxit = 200)
# Every GLM reference is R's own: summary.glm standard errors (Poisson dispersion
# 1, Gamma Pearson), logLik / AIC (Gamma at dispersion deviance/n) and glm's
# null.deviance (intercept-only model WITH the offset; linkinv(offset) without an
# intercept). Issues #54, #55, #56.
emit_glm <- function(name, m, ll = as.numeric(logLik(m)), aic = AIC(m), null_dev = m$null.deviance) {
  s <- summary(m)$coefficients
  cat("// ", deparse(m$call, width.cutoff = 500), "\n", sep = "")
  cat("pub const ", name, "_COEF: [f64; ", length(coef(m)), "] = ", f(coef(m)), ";\n", sep = "")
  cat("pub const ", name, "_SE: [f64; ", nrow(s), "] = ", f(s[, 2]), ";\n", sep = "")
  cat("pub const ", name, "_DEV: [f64; 2] = ", f(c(deviance(m), null_dev)), ";\n", sep = "")
  cat("pub const ", name, "_LL_AIC: [f64; 2] = ", f(c(ll, aic)), ";\n", sep = "")
}
emit_glm("POIS", glm(yp ~ x1 + x2, family = poisson, control = ctl))
emit_glm("POIS_OFF", glm(yp ~ x1 + x2 + offset(off), family = poisson, control = ctl))
emit_glm("POIS_SQRT", glm(yp ~ x1 + x2, family = poisson(link = "sqrt"), start = c(1, 0, 0), control = ctl))
emit_glm("BIN_LOGIT", glm(yb ~ x1 + x2, family = binomial, control = ctl))
emit_glm("BIN_PROBIT", glm(yb ~ x1 + x2, family = binomial(link = "probit"), control = ctl))
emit_glm("BIN_CLOGLOG", glm(yb ~ x1 + x2, family = binomial(link = "cloglog"), control = ctl))
emit_glm("GAMMA", glm(yg ~ x1 + x2, family = Gamma(link = "log"), control = ctl))
# Overdispersed counts (#54): Poisson SEs at dispersion 1, quasipoisson opt-in.
emit_glm("POIS_OVER", glm(ynb ~ x1 + x2, family = poisson, control = ctl))
mq <- glm(ynb ~ x1 + x2, family = quasipoisson, control = ctl)
cat("pub const QPOIS_OVER_SE: [f64; 3] = ", f(summary(mq)$coefficients[, 2]), ";\n", sep = "")
cat("pub const QPOIS_OVER_DISP: f64 = ", num(summary(mq)$dispersion), ";\n", sep = "")
# Null deviance conventions (#56).
emit_glm("POIS_NOINT", glm(yp ~ x1 + x2 - 1, family = poisson, control = ctl))
emit_glm("POIS_NOINT_OFF", glm(yp ~ x1 + x2 - 1 + offset(off), family = poisson, control = ctl))
emit_glm("BIN_OFF", glm(yb ~ x1 + x2 + offset(off), family = binomial, control = ctl))
emit_glm("GAMMA_OFF", glm(yg ~ x1 + x2 + offset(off), family = Gamma(link = "log"), control = ctl))
nb <- glm.nb(ynb ~ x1 + x2, control = ctl)
emit_glm("NB", nb)
cat("pub const NB_THETA: f64 = ", num(nb$theta), ";\n", sep = "")
nbf <- glm(ynb ~ x1 + x2, family = negative.binomial(2.5), control = ctl)
cat("pub const NB_FIXED_COEF: [f64; 3] = ", f(coef(nbf)), ";\n", sep = "")
cat("pub const NB_FIXED_SE: [f64; 3] = ", f(summary(nbf, dispersion = 1)$coefficients[, 2]), ";\n", sep = "")

# Posterior mode of a Poisson GLM with N(0.5, 0.5^2) on x1 and N(0, 0.25^2) on x2
# (flat intercept), and its Laplace covariance solve(X'WX + P).
X <- cbind(1, x1, x2); P <- diag(c(0, 1 / 0.25, 1 / 0.0625)); m0 <- c(0, 0.5, 0)
nlp <- function(b) { eta <- X %*% b; -sum(yp * eta - exp(eta)) + 0.5 * sum(diag(P) * (b - m0)^2) }
b <- coef(glm(yp ~ x1 + x2, family = poisson, control = ctl))
for (i in 1:50) { mu <- as.vector(exp(X %*% b)); H <- t(X) %*% (X * mu) + P
  g <- t(X) %*% (yp - mu) - P %*% (b - m0); b <- b + as.vector(solve(H, g)) }
mu <- as.vector(exp(X %*% b)); I <- t(X) %*% (X * mu); H <- I + P
cat("// Poisson MAP with priors flat, N(0.5, 0.5), N(0, 0.25): Newton in R\n")
cat("pub const POIS_PRIOR_COEF: [f64; 3] = ", f(b), ";\n", sep = "")
cat("pub const POIS_PRIOR_SE_LAPLACE: [f64; 3] = ", f(sqrt(diag(solve(H)))), ";\n", sep = "")
S <- solve(H) %*% I %*% solve(H)
cat("pub const POIS_PRIOR_SE_SANDWICH: [f64; 3] = ", f(sqrt(diag(S))), ";\n", sep = "")
cat("pub const POIS_PRIOR_SE_NAIVE: [f64; 3] = ", f(sqrt(diag(solve(I)))), ";\n\n", sep = "")

for (d in c("weibull", "lognormal", "loglogistic", "exponential")) {
  m <- survreg(Surv(time, ev) ~ x1 + x2, dist = d)
  N <- toupper(d)
  cat("// survreg(Surv(time, ev) ~ x1 + x2, dist = '", d, "')\n", sep = "")
  cat("pub const AFT_", N, "_COEF: [f64; 3] = ", f(coef(m)), ";\n", sep = "")
  cat("pub const AFT_", N, "_SCALE: f64 = ", num(m$scale), ";\n", sep = "")
  cat("pub const AFT_", N, "_LL: [f64; 2] = ", f(m$loglik), ";\n", sep = "")
  cat("pub const AFT_", N, "_SE: [f64; ", nrow(vcov(m)), "] = ", f(sqrt(diag(vcov(m)))), ";\n", sep = "")
  lp <- c(1, 0.3, -0.2) %*% coef(m)
  q <- predict(m, newdata = data.frame(x1 = 0.3, x2 = -0.2), type = "quantile", p = c(0.25, 0.5, 0.9))
  cat("pub const AFT_", N, "_Q: [f64; 3] = ", f(q), ";\n", sep = "")
}
